#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Skobbler.SDKDemo.Resource", IsApplication=true)]

namespace Skobbler.SDKDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050002
			public const int distance_unit = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int distance_unit_values = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int navigation_type = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int navigation_type_value = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int number_routes = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int number_routes_values = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int real_reach_measurement_unit = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int real_reach_online_offline_hybrid = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int road_blocks_in_feet = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int road_blocks_in_meters = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int road_blocks_in_yards = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int route_types = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int route_values = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060005
			public const int black = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int blue_filling = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int blue_outline = 2131099649;
			
			// aapt resource value: 0x7f060020
			public const int blue_panel_day_background = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int blue_panel_night_background = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int blue_panel_night_text = 2131099682;
			
			// aapt resource value: 0x7f060014
			public const int bullet_gray = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int bullet_green = 2131099669;
			
			// aapt resource value: 0x7f060002
			public const int darker_grey = 2131099650;
			
			// aapt resource value: 0x7f060013
			public const int gray = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int green = 2131099665;
			
			// aapt resource value: 0x7f06001d
			public const int green_panel_day_background = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int green_panel_night_background = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int green_panel_night_text = 2131099679;
			
			// aapt resource value: 0x7f060003
			public const int grey = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int grey_options_group = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int light_orange = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int list_text_color = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int menu_bar_header_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int menu_bar_item_text = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int menu_bar_separator_color = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int navigate_blue_button = 2131099664;
			
			// aapt resource value: 0x7f06001c
			public const int navigation_bottom_bar_day = 2131099676;
			
			// aapt resource value: 0x7f060018
			public const int navigation_next_advice_overlay_background = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int navigation_semitransparent_separator = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int navigation_style_day = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int navigation_style_night = 2131099675;
			
			// aapt resource value: 0x7f060008
			public const int orange = 2131099656;
			
			// aapt resource value: 0x7f060012
			public const int red = 2131099666;
			
			// aapt resource value: 0x7f060007
			public const int selected = 2131099655;
			
			// aapt resource value: 0x7f060016
			public const int speed_exceeded = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int speed_panel_night_background = 2131099673;
			
			// aapt resource value: 0x7f06000f
			public const int top_bar_color = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int transparent = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int white = 2131099654;
			
			// aapt resource value: 0x7f060023
			public const int yellow_panel_day_background = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int yellow_panel_night_background = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int yellow_panel_night_text = 2131099685;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f09000d
			public const int action_bar_size = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int alternate_routes_top_bar_size = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int alternate_routes_total_delay_panel_size = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int map_controls_background_size = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int map_controls_button_size = 2131296273;
			
			// aapt resource value: 0x7f090017
			public const int navigation_bottom_panel_height = 2131296279;
			
			// aapt resource value: 0x7f09000b
			public const int navigation_bottom_panel_landscape_height = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int navigation_bottom_text_sub_title_size = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int navigation_bottom_text_title_size = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int navigation_current_advice_panel_landscape_height = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int navigation_current_advice_panel_portrait_width = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int navigation_current_image_landscape = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int navigation_current_image_portrait = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int navigation_next_advice_panel_portrait_height = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int navigation_next_image_landscape = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int navigation_next_image_portrait = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int navigation_panel_landscape_height = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int navigation_panel_landscape_width = 2131296268;
			
			// aapt resource value: 0x7f090016
			public const int navigation_panel_width_height = 2131296278;
			
			// aapt resource value: 0x7f090004
			public const int navigation_speed_limit_speed_cam = 2131296260;
			
			// aapt resource value: 0x7f09000e
			public const int promotion_progress_wheel = 2131296270;
			
			// aapt resource value: 0x7f090015
			public const int text_view_large = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int text_view_medium = 2131296276;
			
			// aapt resource value: 0x7f090013
			public const int text_view_small = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_right = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_alert_sign = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_alert_sign_us = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background_speed_sign = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background_speed_sign_us = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bullet_gray = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bullet_green = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_background_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_selector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cancel = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dot_full = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int download = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int drawer_shadow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_2d = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_3d = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_alert_exclamationmark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_audio_off = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_audio_on = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_back_arrow = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_contribute = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_daymode = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_destination_advise_black = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_destination_advise_white = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_launcher = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_nav_arrow = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_nightmode = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_no_gps = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_overview = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_panning = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_quit = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_roadblock = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_roadblock_inact = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_routeinfo = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_zoom_in = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_zoom_out = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int icon_arrow_list = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int icon_compass = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int icon_dropdownmenu_bike = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int icon_dropdownmenu_car = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon_dropdownmenu_pedestrian = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int icon_historical_positions = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int icon_map_popup_navigate = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int icon_north_oriented = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int icon_position_me = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int icon_searchcenter_favorite = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int list_item_selector = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int logo_skobbler_by_scout = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int map_background = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int menu_bar_header_background = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int menu_bar_item_selector = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int menu_options_selector = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int option_background = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int pause = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int play = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int rounded_corners = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int scrubber_control_disabled_holo = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int scrubber_control_focused_holo = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int scrubber_control_normal_holo = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int scrubber_control_pressed_holo = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int scrubber_primary_holo = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int scrubber_secondary_holo = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int scrubber_track_holo_dark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int splashscreen_background = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int texture_map_unavailable = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int toggle_selector = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int volume_seekbar = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int volume_thumb_selector = 2130837571;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0093
			public const int alt_route_1 = 2131361939;
			
			// aapt resource value: 0x7f0a0094
			public const int alt_route_2 = 2131361940;
			
			// aapt resource value: 0x7f0a0095
			public const int alt_route_3 = 2131361941;
			
			// aapt resource value: 0x7f0a000e
			public const int alt_routes = 2131361806;
			
			// aapt resource value: 0x7f0a0081
			public const int alternative_routes_layout = 2131361921;
			
			// aapt resource value: 0x7f0a0092
			public const int alternative_routes_layout_traffic = 2131361938;
			
			// aapt resource value: 0x7f0a0050
			public const int arriving_distance_text = 2131361872;
			
			// aapt resource value: 0x7f0a0051
			public const int arriving_distance_text_value = 2131361873;
			
			// aapt resource value: 0x7f0a0038
			public const int arriving_time_text = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public const int arriving_time_text_ampm = 2131361849;
			
			// aapt resource value: 0x7f0a0026
			public const int arrow = 2131361830;
			
			// aapt resource value: 0x7f0a0011
			public const int bottom_button = 2131361809;
			
			// aapt resource value: 0x7f0a00ad
			public const int bottom_text = 2131361965;
			
			// aapt resource value: 0x7f0a00a5
			public const int calculate_routes_button = 2131361957;
			
			// aapt resource value: 0x7f0a002d
			public const int cancel = 2131361837;
			
			// aapt resource value: 0x7f0a0004
			public const int cancel_all_button = 2131361796;
			
			// aapt resource value: 0x7f0a0087
			public const int cancel_pre_navigation_button = 2131361927;
			
			// aapt resource value: 0x7f0a000c
			public const int chess_board_background = 2131361804;
			
			// aapt resource value: 0x7f0a00a4
			public const int clear_via_point_button = 2131361956;
			
			// aapt resource value: 0x7f0a0008
			public const int contentFrameLayout = 2131361800;
			
			// aapt resource value: 0x7f0a003f
			public const int current_advice_distance_text = 2131361855;
			
			// aapt resource value: 0x7f0a003c
			public const int current_advice_image_holder = 2131361852;
			
			// aapt resource value: 0x7f0a003d
			public const int current_advice_image_turn = 2131361853;
			
			// aapt resource value: 0x7f0a0040
			public const int current_advice_street_text = 2131361856;
			
			// aapt resource value: 0x7f0a003e
			public const int current_advice_text_holder = 2131361854;
			
			// aapt resource value: 0x7f0a002e
			public const int current_state = 2131361838;
			
			// aapt resource value: 0x7f0a0014
			public const int customView = 2131361812;
			
			// aapt resource value: 0x7f0a009a
			public const int custom_layout = 2131361946;
			
			// aapt resource value: 0x7f0a0001
			public const int download_button = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int download_percentage_text = 2131361794;
			
			// aapt resource value: 0x7f0a002f
			public const int download_progress = 2131361839;
			
			// aapt resource value: 0x7f0a0000
			public const int download_progress_bar = 2131361792;
			
			// aapt resource value: 0x7f0a00b1
			public const int draw_button = 2131361969;
			
			// aapt resource value: 0x7f0a0007
			public const int drawer_layout = 2131361799;
			
			// aapt resource value: 0x7f0a003a
			public const int estimated_navigation_time_text = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int estimated_navigation_time_text_value = 2131361851;
			
			// aapt resource value: 0x7f0a0082
			public const int first_route = 2131361922;
			
			// aapt resource value: 0x7f0a000a
			public const int frameLayout = 2131361802;
			
			// aapt resource value: 0x7f0a007a
			public const int free_drive_current_speed_linear_layout = 2131361914;
			
			// aapt resource value: 0x7f0a007b
			public const int free_drive_current_speed_text = 2131361915;
			
			// aapt resource value: 0x7f0a007c
			public const int free_drive_current_speed_text_value = 2131361916;
			
			// aapt resource value: 0x7f0a0034
			public const int free_drive_current_street_text = 2131361844;
			
			// aapt resource value: 0x7f0a0025
			public const int gpx_chicago = 2131361829;
			
			// aapt resource value: 0x7f0a0021
			public const int gpx_route_1 = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int gpx_route_2 = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int gpx_route_3 = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int gpx_route_4 = 2131361828;
			
			// aapt resource value: 0x7f0a0013
			public const int heading_button = 2131361811;
			
			// aapt resource value: 0x7f0a0073
			public const int increase_decrease_layout = 2131361907;
			
			// aapt resource value: 0x7f0a00b0
			public const int indicator_children_available = 2131361968;
			
			// aapt resource value: 0x7f0a00b2
			public const int label_list_item = 2131361970;
			
			// aapt resource value: 0x7f0a0006
			public const int label_operation_in_progress = 2131361798;
			
			// aapt resource value: 0x7f0a001b
			public const int latitude = 2131361819;
			
			// aapt resource value: 0x7f0a001a
			public const int latitude_field = 2131361818;
			
			// aapt resource value: 0x7f0a0015
			public const int left_drawer = 2131361813;
			
			// aapt resource value: 0x7f0a00aa
			public const int left_image = 2131361962;
			
			// aapt resource value: 0x7f0a0027
			public const int left_layout = 2131361831;
			
			// aapt resource value: 0x7f0a0089
			public const int linearLayout1 = 2131361929;
			
			// aapt resource value: 0x7f0a0003
			public const int list_view = 2131361795;
			
			// aapt resource value: 0x7f0a001d
			public const int longitude = 2131361821;
			
			// aapt resource value: 0x7f0a001c
			public const int longitude_field = 2131361820;
			
			// aapt resource value: 0x7f0a0009
			public const int map_layout_root = 2131361801;
			
			// aapt resource value: 0x7f0a009b
			public const int map_style_day = 2131361947;
			
			// aapt resource value: 0x7f0a009e
			public const int map_style_grayscale = 2131361950;
			
			// aapt resource value: 0x7f0a009c
			public const int map_style_night = 2131361948;
			
			// aapt resource value: 0x7f0a009d
			public const int map_style_outdoor = 2131361949;
			
			// aapt resource value: 0x7f0a000f
			public const int map_styles = 2131361807;
			
			// aapt resource value: 0x7f0a0072
			public const int menu_back_follower_mode_button = 2131361906;
			
			// aapt resource value: 0x7f0a0086
			public const int menu_back_prenavigation_button = 2131361926;
			
			// aapt resource value: 0x7f0a00ab
			public const int mid_layout = 2131361963;
			
			// aapt resource value: 0x7f0a002b
			public const int middle_layout = 2131361835;
			
			// aapt resource value: 0x7f0a005c
			public const int nav_settings_first_row = 2131361884;
			
			// aapt resource value: 0x7f0a006b
			public const int nav_settings_forth_row = 2131361899;
			
			// aapt resource value: 0x7f0a0061
			public const int nav_settings_second_row = 2131361889;
			
			// aapt resource value: 0x7f0a0066
			public const int nav_settings_third_row = 2131361894;
			
			// aapt resource value: 0x7f0a0078
			public const int navigation_alert_sign_image = 2131361912;
			
			// aapt resource value: 0x7f0a0042
			public const int navigation_bottom_right_arriving_panel = 2131361858;
			
			// aapt resource value: 0x7f0a0041
			public const int navigation_bottom_right_estimated_panel = 2131361857;
			
			// aapt resource value: 0x7f0a0044
			public const int navigation_contribute_option_text = 2131361860;
			
			// aapt resource value: 0x7f0a0075
			public const int navigation_decrease_speed = 2131361909;
			
			// aapt resource value: 0x7f0a0076
			public const int navigation_free_drive_speed_limit_panel = 2131361910;
			
			// aapt resource value: 0x7f0a0074
			public const int navigation_increase_speed = 2131361908;
			
			// aapt resource value: 0x7f0a0048
			public const int navigation_next_advice_image_distance_overlay_background = 2131361864;
			
			// aapt resource value: 0x7f0a004b
			public const int navigation_next_advice_street_overlay_background = 2131361867;
			
			// aapt resource value: 0x7f0a0054
			public const int navigation_route_overview_current_position_label = 2131361876;
			
			// aapt resource value: 0x7f0a0055
			public const int navigation_route_overview_current_position_text = 2131361877;
			
			// aapt resource value: 0x7f0a0057
			public const int navigation_route_overview_destination_label = 2131361879;
			
			// aapt resource value: 0x7f0a0056
			public const int navigation_route_overview_destination_layout = 2131361878;
			
			// aapt resource value: 0x7f0a0058
			public const int navigation_route_overview_destination_text = 2131361880;
			
			// aapt resource value: 0x7f0a0052
			public const int navigation_route_overview_linear_layout = 2131361874;
			
			// aapt resource value: 0x7f0a0053
			public const int navigation_route_overview_starting_position_layout = 2131361875;
			
			// aapt resource value: 0x7f0a0059
			public const int navigation_searching_for_gps_text = 2131361881;
			
			// aapt resource value: 0x7f0a005d
			public const int navigation_settings_audio_button = 2131361885;
			
			// aapt resource value: 0x7f0a005e
			public const int navigation_settings_audio_text = 2131361886;
			
			// aapt resource value: 0x7f0a005a
			public const int navigation_settings_back_button = 2131361882;
			
			// aapt resource value: 0x7f0a005f
			public const int navigation_settings_day_night_mode_button = 2131361887;
			
			// aapt resource value: 0x7f0a0060
			public const int navigation_settings_day_night_mode_text = 2131361888;
			
			// aapt resource value: 0x7f0a0043
			public const int navigation_settings_option_text = 2131361859;
			
			// aapt resource value: 0x7f0a0062
			public const int navigation_settings_overview_button = 2131361890;
			
			// aapt resource value: 0x7f0a0063
			public const int navigation_settings_overview_text = 2131361891;
			
			// aapt resource value: 0x7f0a0069
			public const int navigation_settings_panning_button = 2131361897;
			
			// aapt resource value: 0x7f0a006a
			public const int navigation_settings_panning_text = 2131361898;
			
			// aapt resource value: 0x7f0a006e
			public const int navigation_settings_quit_button = 2131361902;
			
			// aapt resource value: 0x7f0a006f
			public const int navigation_settings_quit_text = 2131361903;
			
			// aapt resource value: 0x7f0a0067
			public const int navigation_settings_roadblock_info_button = 2131361895;
			
			// aapt resource value: 0x7f0a0068
			public const int navigation_settings_roadblock_info_text = 2131361896;
			
			// aapt resource value: 0x7f0a0064
			public const int navigation_settings_route_info_button = 2131361892;
			
			// aapt resource value: 0x7f0a0065
			public const int navigation_settings_route_info_text = 2131361893;
			
			// aapt resource value: 0x7f0a005b
			public const int navigation_settings_seek_bar_layout = 2131361883;
			
			// aapt resource value: 0x7f0a006c
			public const int navigation_settings_view_mode_button = 2131361900;
			
			// aapt resource value: 0x7f0a006d
			public const int navigation_settings_view_mode_text = 2131361901;
			
			// aapt resource value: 0x7f0a0070
			public const int navigation_settings_volume = 2131361904;
			
			// aapt resource value: 0x7f0a0071
			public const int navigation_settings_volume_text = 2131361905;
			
			// aapt resource value: 0x7f0a0077
			public const int navigation_speed_sign_image = 2131361911;
			
			// aapt resource value: 0x7f0a0037
			public const int navigation_top_back_button = 2131361847;
			
			// aapt resource value: 0x7f0a009f
			public const int navigation_ui_back_button = 2131361951;
			
			// aapt resource value: 0x7f0a00a0
			public const int navigation_ui_buttons = 2131361952;
			
			// aapt resource value: 0x7f0a0010
			public const int navigation_ui_layout = 2131361808;
			
			// aapt resource value: 0x7f0a0035
			public const int navmenu_item_label = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int navmenusection_label = 2131361846;
			
			// aapt resource value: 0x7f0a0047
			public const int next_advice_distance_text = 2131361863;
			
			// aapt resource value: 0x7f0a004a
			public const int next_advice_street_name_text = 2131361866;
			
			// aapt resource value: 0x7f0a0049
			public const int next_advice_street_name_text_layout = 2131361865;
			
			// aapt resource value: 0x7f0a0046
			public const int next_image_turn_advice = 2131361862;
			
			// aapt resource value: 0x7f0a0045
			public const int next_image_turn_advice_distance_layout = 2131361861;
			
			// aapt resource value: 0x7f0a002a
			public const int package_name = 2131361834;
			
			// aapt resource value: 0x7f0a0029
			public const int package_size = 2131361833;
			
			// aapt resource value: 0x7f0a007f
			public const int pedestrian_compass_panel_image_view = 2131361919;
			
			// aapt resource value: 0x7f0a007e
			public const int pedestrian_compass_panel_layout = 2131361918;
			
			// aapt resource value: 0x7f0a0031
			public const int percentage = 2131361841;
			
			// aapt resource value: 0x7f0a00a9
			public const int popup_layout = 2131361961;
			
			// aapt resource value: 0x7f0a0012
			public const int position_me_button = 2131361810;
			
			// aapt resource value: 0x7f0a00a8
			public const int position_me_navigation_ui_button = 2131361960;
			
			// aapt resource value: 0x7f0a0080
			public const int position_me_real_navigation_button = 2131361920;
			
			// aapt resource value: 0x7f0a0030
			public const int progress_details = 2131361840;
			
			// aapt resource value: 0x7f0a0017
			public const int radius = 2131361815;
			
			// aapt resource value: 0x7f0a0016
			public const int radius_field = 2131361814;
			
			// aapt resource value: 0x7f0a004c
			public const int re_routing_text = 2131361868;
			
			// aapt resource value: 0x7f0a008e
			public const int real_reach_bike_button = 2131361934;
			
			// aapt resource value: 0x7f0a008f
			public const int real_reach_car_button = 2131361935;
			
			// aapt resource value: 0x7f0a0090
			public const int real_reach_online_offline_hybrid = 2131361936;
			
			// aapt resource value: 0x7f0a008d
			public const int real_reach_pedestrian_button = 2131361933;
			
			// aapt resource value: 0x7f0a0091
			public const int real_reach_round_trip = 2131361937;
			
			// aapt resource value: 0x7f0a008b
			public const int real_reach_seekbar = 2131361931;
			
			// aapt resource value: 0x7f0a0088
			public const int real_reach_spinner = 2131361928;
			
			// aapt resource value: 0x7f0a008a
			public const int real_reach_time = 2131361930;
			
			// aapt resource value: 0x7f0a000d
			public const int real_reach_time_layout = 2131361805;
			
			// aapt resource value: 0x7f0a008c
			public const int real_reach_vehicle_layout = 2131361932;
			
			// aapt resource value: 0x7f0a001f
			public const int reverse_geocode_button = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int reverse_geocoding_result = 2131361824;
			
			// aapt resource value: 0x7f0a004d
			public const int road_block_relative_layout = 2131361869;
			
			// aapt resource value: 0x7f0a004e
			public const int roadblock_list = 2131361870;
			
			// aapt resource value: 0x7f0a004f
			public const int route_distance_linear_layout = 2131361871;
			
			// aapt resource value: 0x7f0a0097
			public const int route_info_0 = 2131361943;
			
			// aapt resource value: 0x7f0a0098
			public const int route_info_1 = 2131361944;
			
			// aapt resource value: 0x7f0a0099
			public const int route_info_2 = 2131361945;
			
			// aapt resource value: 0x7f0a0096
			public const int route_info_layout = 2131361942;
			
			// aapt resource value: 0x7f0a001e
			public const int search_button = 2131361822;
			
			// aapt resource value: 0x7f0a0019
			public const int search_topic = 2131361817;
			
			// aapt resource value: 0x7f0a0018
			public const int search_topic_field = 2131361816;
			
			// aapt resource value: 0x7f0a0083
			public const int second_route = 2131361923;
			
			// aapt resource value: 0x7f0a00a2
			public const int select_end_point_button = 2131361954;
			
			// aapt resource value: 0x7f0a00a1
			public const int select_start_point_button = 2131361953;
			
			// aapt resource value: 0x7f0a00a3
			public const int select_via_point_button = 2131361955;
			
			// aapt resource value: 0x7f0a00a7
			public const int settings_button = 2131361959;
			
			// aapt resource value: 0x7f0a0005
			public const int show_heat_map = 2131361797;
			
			// aapt resource value: 0x7f0a0033
			public const int speed = 2131361843;
			
			// aapt resource value: 0x7f0a0079
			public const int speed_limit_value = 2131361913;
			
			// aapt resource value: 0x7f0a00a6
			public const int start_free_drive_button = 2131361958;
			
			// aapt resource value: 0x7f0a0085
			public const int start_navigation_button = 2131361925;
			
			// aapt resource value: 0x7f0a002c
			public const int start_pause = 2131361836;
			
			// aapt resource value: 0x7f0a00af
			public const int subtitle = 2131361967;
			
			// aapt resource value: 0x7f0a0084
			public const int third_route = 2131361924;
			
			// aapt resource value: 0x7f0a0032
			public const int time_left = 2131361842;
			
			// aapt resource value: 0x7f0a00ae
			public const int title = 2131361966;
			
			// aapt resource value: 0x7f0a0028
			public const int top_layout = 2131361832;
			
			// aapt resource value: 0x7f0a00ac
			public const int top_text = 2131361964;
			
			// aapt resource value: 0x7f0a007d
			public const int via_point_text_view = 2131361917;
			
			// aapt resource value: 0x7f0a000b
			public const int view_group_map = 2131361803;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_download = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_downloads_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_list = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_map = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_map_cache = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_nearby_search = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_reverse_geocoding = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_splash = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_tracks = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int download_list_activity = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int element_download_list_item = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int element_free_drive_current_street_panel = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int element_menu_drawer_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int element_menu_drawer_section = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int element_navigation_back_button = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int element_navigation_bottom_right_arriving_panel = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int element_navigation_bottom_right_estimated_panel = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int element_navigation_current_advice_panel = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int element_navigation_eta_arriving_group_panels = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int element_navigation_menu_options = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int element_navigation_next_advice_panel = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int element_navigation_rerouting_panel = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int element_navigation_roadblocks_list = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int element_navigation_route_distance = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int element_navigation_route_overview_panel = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int element_navigation_searching_for_gps = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int element_navigation_settings = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int element_navigation_simulation_buttons = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int element_navigation_speed_panel = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int element_navigation_via_point_panel = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int element_pedestrian_compass_panel = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int element_position_me_button = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int element_pre_navigation_buttons_panel = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int element_real_reach_time = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int layout_alternative_routes = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int layout_custom_view = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int layout_map_styles = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int layout_navigation_ui = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int layout_popup = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int layout_search_list_item = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int layout_track_element_list_item = 2130903081;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f07002b
			public const int calculate_route = 2131165227;
			
			// aapt resource value: 0x7f070040
			public const int calculate_routes = 2131165248;
			
			// aapt resource value: 0x7f07004a
			public const int cancel_all_downloads = 2131165258;
			
			// aapt resource value: 0x7f070038
			public const int cancel_label = 2131165240;
			
			// aapt resource value: 0x7f070024
			public const int city = 2131165220;
			
			// aapt resource value: 0x7f070048
			public const int clear_via_point = 2131165256;
			
			// aapt resource value: 0x7f070074
			public const int close_drawer = 2131165300;
			
			// aapt resource value: 0x7f070023
			public const int country_code = 2131165219;
			
			// aapt resource value: 0x7f0700a0
			public const int current_position = 2131165344;
			
			// aapt resource value: 0x7f070088
			public const int decrease_speed = 2131165320;
			
			// aapt resource value: 0x7f070081
			public const int destination_label = 2131165313;
			
			// aapt resource value: 0x7f07008c
			public const int destination_reached_info_text = 2131165324;
			
			// aapt resource value: 0x7f0700a3
			public const int distance_time = 2131165347;
			
			// aapt resource value: 0x7f0700a5
			public const int download_cancel = 2131165349;
			
			// aapt resource value: 0x7f0700a6
			public const int download_pause = 2131165350;
			
			// aapt resource value: 0x7f0700a7
			public const int download_resume = 2131165351;
			
			// aapt resource value: 0x7f0700a4
			public const int download_start = 2131165348;
			
			// aapt resource value: 0x7f07003f
			public const int end_point_nav = 2131165247;
			
			// aapt resource value: 0x7f070080
			public const int exit_highway_advice_label = 2131165312;
			
			// aapt resource value: 0x7f07008a
			public const int exit_navigation_dialog_message = 2131165322;
			
			// aapt resource value: 0x7f07008b
			public const int exit_navigation_dialog_title = 2131165323;
			
			// aapt resource value: 0x7f07007d
			public const int feet_label = 2131165309;
			
			// aapt resource value: 0x7f07006b
			public const int fifteen = 2131165291;
			
			// aapt resource value: 0x7f070071
			public const int fifteen_mi_h = 2131165297;
			
			// aapt resource value: 0x7f070069
			public const int five = 2131165289;
			
			// aapt resource value: 0x7f07006f
			public const int five_mi_h = 2131165295;
			
			// aapt resource value: 0x7f070058
			public const int general_label = 2131165272;
			
			// aapt resource value: 0x7f070035
			public const int gpx_license_notification_text = 2131165237;
			
			// aapt resource value: 0x7f070039
			public const int gpx_route_1 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int gpx_route_2 = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int gpx_route_3 = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int gpx_route_4 = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int gpx_route_5 = 2131165245;
			
			// aapt resource value: 0x7f070076
			public const int hour_value = 2131165302;
			
			// aapt resource value: 0x7f070026
			public const int house_number = 2131165222;
			
			// aapt resource value: 0x7f070087
			public const int increase_speed = 2131165319;
			
			// aapt resource value: 0x7f07007e
			public const int km_label = 2131165310;
			
			// aapt resource value: 0x7f070060
			public const int km_m = 2131165280;
			
			// aapt resource value: 0x7f070079
			public const int kmh_label = 2131165305;
			
			// aapt resource value: 0x7f07001e
			public const int label_download = 2131165214;
			
			// aapt resource value: 0x7f07002e
			public const int label_draw = 2131165230;
			
			// aapt resource value: 0x7f070031
			public const int label_heading = 2131165233;
			
			// aapt resource value: 0x7f07001d
			public const int label_parsing_xml = 2131165213;
			
			// aapt resource value: 0x7f070030
			public const int label_position_me = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int label_route = 2131165231;
			
			// aapt resource value: 0x7f070020
			public const int latitude = 2131165216;
			
			// aapt resource value: 0x7f07006d
			public const int less = 2131165293;
			
			// aapt resource value: 0x7f070046
			public const int long_tap_for_position = 2131165254;
			
			// aapt resource value: 0x7f070021
			public const int longitude = 2131165217;
			
			// aapt resource value: 0x7f070018
			public const int map_style_day = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int map_style_grayscale = 2131165211;
			
			// aapt resource value: 0x7f070019
			public const int map_style_night = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int map_style_outdoor = 2131165210;
			
			// aapt resource value: 0x7f07007b
			public const int meters_label = 2131165307;
			
			// aapt resource value: 0x7f070061
			public const int mi_feet = 2131165281;
			
			// aapt resource value: 0x7f07007c
			public const int mi_label = 2131165308;
			
			// aapt resource value: 0x7f070062
			public const int mi_yards = 2131165282;
			
			// aapt resource value: 0x7f070077
			public const int minute_value = 2131165303;
			
			// aapt resource value: 0x7f07006e
			public const int more = 2131165294;
			
			// aapt resource value: 0x7f07007a
			public const int mph_label = 2131165306;
			
			// aapt resource value: 0x7f07001c
			public const int navigate = 2131165212;
			
			// aapt resource value: 0x7f07009b
			public const int navigate_settings_2d_view = 2131165339;
			
			// aapt resource value: 0x7f07009c
			public const int navigate_settings_3d_view = 2131165340;
			
			// aapt resource value: 0x7f070094
			public const int navigate_settings_audio_off = 2131165332;
			
			// aapt resource value: 0x7f070095
			public const int navigate_settings_audio_on = 2131165333;
			
			// aapt resource value: 0x7f07009f
			public const int navigate_settings_block_road = 2131165343;
			
			// aapt resource value: 0x7f070097
			public const int navigate_settings_daymode = 2131165335;
			
			// aapt resource value: 0x7f070096
			public const int navigate_settings_nightmode = 2131165334;
			
			// aapt resource value: 0x7f070093
			public const int navigate_settings_overview = 2131165331;
			
			// aapt resource value: 0x7f07009a
			public const int navigate_settings_panning = 2131165338;
			
			// aapt resource value: 0x7f07009e
			public const int navigate_settings_quit = 2131165342;
			
			// aapt resource value: 0x7f070098
			public const int navigate_settings_reload = 2131165336;
			
			// aapt resource value: 0x7f070099
			public const int navigate_settings_routeinfo = 2131165337;
			
			// aapt resource value: 0x7f07009d
			public const int navigate_settings_volume = 2131165341;
			
			// aapt resource value: 0x7f07001f
			public const int no_internet_connection = 2131165215;
			
			// aapt resource value: 0x7f07004c
			public const int no_offline_packages = 2131165260;
			
			// aapt resource value: 0x7f070032
			public const int no_position_available = 2131165234;
			
			// aapt resource value: 0x7f070049
			public const int no_position_message = 2131165257;
			
			// aapt resource value: 0x7f070045
			public const int off_button = 2131165253;
			
			// aapt resource value: 0x7f070075
			public const int ok_label = 2131165301;
			
			// aapt resource value: 0x7f070036
			public const int ok_text = 2131165238;
			
			// aapt resource value: 0x7f070044
			public const int on_button = 2131165252;
			
			// aapt resource value: 0x7f070063
			public const int one_route = 2131165283;
			
			// aapt resource value: 0x7f070073
			public const int open_drawer = 2131165299;
			
			// aapt resource value: 0x7f07000e
			public const int option_address_search = 2131165198;
			
			// aapt resource value: 0x7f07000a
			public const int option_alternative_routes = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int option_annotations = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int option_car_navigation_ui = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int option_category_search = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int option_group_searches = 2131165197;
			
			// aapt resource value: 0x7f070017
			public const int option_heat_map = 2131165207;
			
			// aapt resource value: 0x7f070004
			public const int option_map_creator = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int option_map_display = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int option_map_styles = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int option_map_updates = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int option_map_xml_and_downloads = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int option_nearby_search = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int option_other_map = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int option_overlays = 2131165189;
			
			// aapt resource value: 0x7f070016
			public const int option_pedestrian_navigation_ui = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int option_poi_tracking = 2131165204;
			
			// aapt resource value: 0x7f07000b
			public const int option_real_reach = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int option_reverse_geocoding = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int option_routing_and_navigation = 2131165203;
			
			// aapt resource value: 0x7f07000c
			public const int option_tracks = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int options_group_map = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int options_group_navigation = 2131165193;
			
			// aapt resource value: 0x7f070085
			public const int quit_navigation = 2131165317;
			
			// aapt resource value: 0x7f07002a
			public const int radius = 2131165226;
			
			// aapt resource value: 0x7f070083
			public const int re_routing = 2131165315;
			
			// aapt resource value: 0x7f070066
			public const int real_navigation = 2131165286;
			
			// aapt resource value: 0x7f07004f
			public const int real_reach_choose_type = 2131165263;
			
			// aapt resource value: 0x7f070055
			public const int real_reach_hybrid = 2131165269;
			
			// aapt resource value: 0x7f070054
			public const int real_reach_offline = 2131165268;
			
			// aapt resource value: 0x7f070053
			public const int real_reach_online = 2131165267;
			
			// aapt resource value: 0x7f070052
			public const int real_reach_profile_distance = 2131165266;
			
			// aapt resource value: 0x7f070051
			public const int real_reach_profile_energy = 2131165265;
			
			// aapt resource value: 0x7f070050
			public const int real_reach_profile_time = 2131165264;
			
			// aapt resource value: 0x7f070022
			public const int reverse_geocode = 2131165218;
			
			// aapt resource value: 0x7f070056
			public const int round_trip = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int round_trip_off = 2131165271;
			
			// aapt resource value: 0x7f070033
			public const int route_calculation_failed = 2131165235;
			
			// aapt resource value: 0x7f070091
			public const int route_cannot_be_calculated = 2131165329;
			
			// aapt resource value: 0x7f07008e
			public const int route_invalid_destination = 2131165326;
			
			// aapt resource value: 0x7f07008f
			public const int route_invalid_start = 2131165327;
			
			// aapt resource value: 0x7f07008d
			public const int route_same_start_and_destination = 2131165325;
			
			// aapt resource value: 0x7f07005d
			public const int route_type_bicycle_fast = 2131165277;
			
			// aapt resource value: 0x7f07005f
			public const int route_type_bicycle_quiet = 2131165279;
			
			// aapt resource value: 0x7f07005e
			public const int route_type_bicycle_short = 2131165278;
			
			// aapt resource value: 0x7f07005b
			public const int route_type_car_efficient = 2131165275;
			
			// aapt resource value: 0x7f070059
			public const int route_type_car_fastest = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int route_type_car_shortest = 2131165274;
			
			// aapt resource value: 0x7f07005c
			public const int route_type_pedestrian = 2131165276;
			
			// aapt resource value: 0x7f070090
			public const int route_unknown_server_error = 2131165328;
			
			// aapt resource value: 0x7f070092
			public const int routing_server_error = 2131165330;
			
			// aapt resource value: 0x7f070027
			public const int search = 2131165223;
			
			// aapt resource value: 0x7f070029
			public const int search_topic = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int searching = 2131165224;
			
			// aapt resource value: 0x7f070089
			public const int searching_for_gps_label = 2131165321;
			
			// aapt resource value: 0x7f070078
			public const int seconds_value = 2131165304;
			
			// aapt resource value: 0x7f070047
			public const int select_via_point = 2131165255;
			
			// aapt resource value: 0x7f070084
			public const int settings_label = 2131165316;
			
			// aapt resource value: 0x7f070043
			public const int settings_nav_ui = 2131165251;
			
			// aapt resource value: 0x7f070034
			public const int show_heat_map = 2131165236;
			
			// aapt resource value: 0x7f070068
			public const int sim_from_log_navigation = 2131165288;
			
			// aapt resource value: 0x7f070067
			public const int simulation_navigation = 2131165287;
			
			// aapt resource value: 0x7f070042
			public const int start_free_drive = 2131165250;
			
			// aapt resource value: 0x7f070041
			public const int start_free_walk = 2131165249;
			
			// aapt resource value: 0x7f07002d
			public const int start_navigation = 2131165229;
			
			// aapt resource value: 0x7f07003e
			public const int start_point_nav = 2131165246;
			
			// aapt resource value: 0x7f0700a2
			public const int start_prim_navigation = 2131165346;
			
			// aapt resource value: 0x7f070082
			public const int starting_pos_label = 2131165314;
			
			// aapt resource value: 0x7f07002c
			public const int stop_navigation = 2131165228;
			
			// aapt resource value: 0x7f070025
			public const int street = 2131165221;
			
			// aapt resource value: 0x7f07006a
			public const int ten = 2131165290;
			
			// aapt resource value: 0x7f070070
			public const int ten_mi_h = 2131165296;
			
			// aapt resource value: 0x7f07004d
			public const int test = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int testing = 2131165262;
			
			// aapt resource value: 0x7f07004b
			public const int text_to_speech_engine_not_initialized = 2131165259;
			
			// aapt resource value: 0x7f070065
			public const int three_routes = 2131165285;
			
			// aapt resource value: 0x7f07006c
			public const int twelve = 2131165292;
			
			// aapt resource value: 0x7f070072
			public const int twelve_mi_h = 2131165298;
			
			// aapt resource value: 0x7f070064
			public const int two_routes = 2131165284;
			
			// aapt resource value: 0x7f0700a1
			public const int unblock_all = 2131165345;
			
			// aapt resource value: 0x7f070037
			public const int update_label = 2131165239;
			
			// aapt resource value: 0x7f070086
			public const int via_point_reached = 2131165318;
			
			// aapt resource value: 0x7f07007f
			public const int yards_label = 2131165311;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f08000b
			public const int SplashActivityTheme = 2131230731;
			
			// aapt resource value: 0x7f080003
			public const int alt_routes_button_style = 2131230723;
			
			// aapt resource value: 0x7f080015
			public const int alternate_route_cell_style = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int alternate_route_cell_style_landscape = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int alternate_route_text_holder_style = 2131230743;
			
			// aapt resource value: 0x7f080013
			public const int alternate_route_text_style_normal = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int alternate_route_text_style_tvdpi = 2131230740;
			
			// aapt resource value: 0x7f080004
			public const int button_style = 2131230724;
			
			// aapt resource value: 0x7f08000c
			public const int general_black_button_label_normal_screen = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int general_white_button_label = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int general_white_button_label_normal_screen = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int left_drawer_list = 2131230730;
			
			// aapt resource value: 0x7f080001
			public const int list_items_style = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int menu_bar_header_text = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int menu_bar_header_text_normal_screen = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int menu_bar_item_background = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int menu_bar_item_text = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int menu_bar_item_text_normal_screen = 2131230727;
			
			// aapt resource value: 0x7f080002
			public const int menu_options_group_style = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int menu_options_style = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int navigation_settings_layout = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int navigation_settings_text = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int navigation_settings_text_normal = 2131230738;
			
			// aapt resource value: 0x7f08000f
			public const int pre_navigation_text = 2131230735;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int settings = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
