#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Skobbler.SDKDemo.Resource", IsApplication=true)]

namespace Skobbler.SDKDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Skobbler.SDKTools.Resource.Array.road_blocks_in_feet = global::Skobbler.SDKDemo.Resource.Array.road_blocks_in_feet;
			global::Skobbler.SDKTools.Resource.Array.road_blocks_in_meters = global::Skobbler.SDKDemo.Resource.Array.road_blocks_in_meters;
			global::Skobbler.SDKTools.Resource.Array.road_blocks_in_yards = global::Skobbler.SDKDemo.Resource.Array.road_blocks_in_yards;
			global::Skobbler.SDKTools.Resource.Color.black = global::Skobbler.SDKDemo.Resource.Color.black;
			global::Skobbler.SDKTools.Resource.Color.blue_panel_day_background = global::Skobbler.SDKDemo.Resource.Color.blue_panel_day_background;
			global::Skobbler.SDKTools.Resource.Color.blue_panel_night_background = global::Skobbler.SDKDemo.Resource.Color.blue_panel_night_background;
			global::Skobbler.SDKTools.Resource.Color.blue_panel_night_text = global::Skobbler.SDKDemo.Resource.Color.blue_panel_night_text;
			global::Skobbler.SDKTools.Resource.Color.bullet_gray = global::Skobbler.SDKDemo.Resource.Color.bullet_gray;
			global::Skobbler.SDKTools.Resource.Color.bullet_green = global::Skobbler.SDKDemo.Resource.Color.bullet_green;
			global::Skobbler.SDKTools.Resource.Color.gray = global::Skobbler.SDKDemo.Resource.Color.gray;
			global::Skobbler.SDKTools.Resource.Color.green_panel_day_background = global::Skobbler.SDKDemo.Resource.Color.green_panel_day_background;
			global::Skobbler.SDKTools.Resource.Color.green_panel_night_background = global::Skobbler.SDKDemo.Resource.Color.green_panel_night_background;
			global::Skobbler.SDKTools.Resource.Color.green_panel_night_text = global::Skobbler.SDKDemo.Resource.Color.green_panel_night_text;
			global::Skobbler.SDKTools.Resource.Color.navigation_next_advice_overlay_background = global::Skobbler.SDKDemo.Resource.Color.navigation_next_advice_overlay_background;
			global::Skobbler.SDKTools.Resource.Color.navigation_semitransparent_separator = global::Skobbler.SDKDemo.Resource.Color.navigation_semitransparent_separator;
			global::Skobbler.SDKTools.Resource.Color.navigation_style_day = global::Skobbler.SDKDemo.Resource.Color.navigation_style_day;
			global::Skobbler.SDKTools.Resource.Color.navigation_style_night = global::Skobbler.SDKDemo.Resource.Color.navigation_style_night;
			global::Skobbler.SDKTools.Resource.Color.red = global::Skobbler.SDKDemo.Resource.Color.red;
			global::Skobbler.SDKTools.Resource.Color.speed_exceeded = global::Skobbler.SDKDemo.Resource.Color.speed_exceeded;
			global::Skobbler.SDKTools.Resource.Color.speed_panel_night_background = global::Skobbler.SDKDemo.Resource.Color.speed_panel_night_background;
			global::Skobbler.SDKTools.Resource.Color.white = global::Skobbler.SDKDemo.Resource.Color.white;
			global::Skobbler.SDKTools.Resource.Color.yellow_panel_day_background = global::Skobbler.SDKDemo.Resource.Color.yellow_panel_day_background;
			global::Skobbler.SDKTools.Resource.Color.yellow_panel_night_background = global::Skobbler.SDKDemo.Resource.Color.yellow_panel_night_background;
			global::Skobbler.SDKTools.Resource.Color.yellow_panel_night_text = global::Skobbler.SDKDemo.Resource.Color.yellow_panel_night_text;
			global::Skobbler.SDKTools.Resource.Dimension.action_bar_size = global::Skobbler.SDKDemo.Resource.Dimension.action_bar_size;
			global::Skobbler.SDKTools.Resource.Dimension.alternate_routes_top_bar_size = global::Skobbler.SDKDemo.Resource.Dimension.alternate_routes_top_bar_size;
			global::Skobbler.SDKTools.Resource.Dimension.alternate_routes_total_delay_panel_size = global::Skobbler.SDKDemo.Resource.Dimension.alternate_routes_total_delay_panel_size;
			global::Skobbler.SDKTools.Resource.Dimension.map_controls_background_size = global::Skobbler.SDKDemo.Resource.Dimension.map_controls_background_size;
			global::Skobbler.SDKTools.Resource.Dimension.map_controls_button_size = global::Skobbler.SDKDemo.Resource.Dimension.map_controls_button_size;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_bottom_panel_height = global::Skobbler.SDKDemo.Resource.Dimension.navigation_bottom_panel_height;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_bottom_text_sub_title_size = global::Skobbler.SDKDemo.Resource.Dimension.navigation_bottom_text_sub_title_size;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_bottom_text_title_size = global::Skobbler.SDKDemo.Resource.Dimension.navigation_bottom_text_title_size;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_current_advice_panel_landscape_height = global::Skobbler.SDKDemo.Resource.Dimension.navigation_current_advice_panel_landscape_height;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_current_advice_panel_portrait_width = global::Skobbler.SDKDemo.Resource.Dimension.navigation_current_advice_panel_portrait_width;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_current_image_landscape = global::Skobbler.SDKDemo.Resource.Dimension.navigation_current_image_landscape;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_current_image_portrait = global::Skobbler.SDKDemo.Resource.Dimension.navigation_current_image_portrait;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_next_advice_panel_portrait_height = global::Skobbler.SDKDemo.Resource.Dimension.navigation_next_advice_panel_portrait_height;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_next_image_landscape = global::Skobbler.SDKDemo.Resource.Dimension.navigation_next_image_landscape;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_next_image_portrait = global::Skobbler.SDKDemo.Resource.Dimension.navigation_next_image_portrait;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_panel_landscape_height = global::Skobbler.SDKDemo.Resource.Dimension.navigation_panel_landscape_height;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_panel_landscape_width = global::Skobbler.SDKDemo.Resource.Dimension.navigation_panel_landscape_width;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_panel_width_height = global::Skobbler.SDKDemo.Resource.Dimension.navigation_panel_width_height;
			global::Skobbler.SDKTools.Resource.Dimension.navigation_speed_limit_speed_cam = global::Skobbler.SDKDemo.Resource.Dimension.navigation_speed_limit_speed_cam;
			global::Skobbler.SDKTools.Resource.Dimension.promotion_progress_wheel = global::Skobbler.SDKDemo.Resource.Dimension.promotion_progress_wheel;
			global::Skobbler.SDKTools.Resource.Dimension.text_view_large = global::Skobbler.SDKDemo.Resource.Dimension.text_view_large;
			global::Skobbler.SDKTools.Resource.Dimension.text_view_medium = global::Skobbler.SDKDemo.Resource.Dimension.text_view_medium;
			global::Skobbler.SDKTools.Resource.Dimension.text_view_small = global::Skobbler.SDKDemo.Resource.Dimension.text_view_small;
			global::Skobbler.SDKTools.Resource.Drawable.background_alert_sign = global::Skobbler.SDKDemo.Resource.Drawable.background_alert_sign;
			global::Skobbler.SDKTools.Resource.Drawable.background_alert_sign_us = global::Skobbler.SDKDemo.Resource.Drawable.background_alert_sign_us;
			global::Skobbler.SDKTools.Resource.Drawable.background_speed_sign = global::Skobbler.SDKDemo.Resource.Drawable.background_speed_sign;
			global::Skobbler.SDKTools.Resource.Drawable.background_speed_sign_us = global::Skobbler.SDKDemo.Resource.Drawable.background_speed_sign_us;
			global::Skobbler.SDKTools.Resource.Drawable.bullet_gray = global::Skobbler.SDKDemo.Resource.Drawable.bullet_gray;
			global::Skobbler.SDKTools.Resource.Drawable.bullet_green = global::Skobbler.SDKDemo.Resource.Drawable.bullet_green;
			global::Skobbler.SDKTools.Resource.Drawable.ic_2d = global::Skobbler.SDKDemo.Resource.Drawable.ic_2d;
			global::Skobbler.SDKTools.Resource.Drawable.ic_3d = global::Skobbler.SDKDemo.Resource.Drawable.ic_3d;
			global::Skobbler.SDKTools.Resource.Drawable.ic_alert_exclamationmark = global::Skobbler.SDKDemo.Resource.Drawable.ic_alert_exclamationmark;
			global::Skobbler.SDKTools.Resource.Drawable.ic_audio_off = global::Skobbler.SDKDemo.Resource.Drawable.ic_audio_off;
			global::Skobbler.SDKTools.Resource.Drawable.ic_audio_on = global::Skobbler.SDKDemo.Resource.Drawable.ic_audio_on;
			global::Skobbler.SDKTools.Resource.Drawable.ic_back_arrow = global::Skobbler.SDKDemo.Resource.Drawable.ic_back_arrow;
			global::Skobbler.SDKTools.Resource.Drawable.ic_contribute = global::Skobbler.SDKDemo.Resource.Drawable.ic_contribute;
			global::Skobbler.SDKTools.Resource.Drawable.ic_daymode = global::Skobbler.SDKDemo.Resource.Drawable.ic_daymode;
			global::Skobbler.SDKTools.Resource.Drawable.ic_destination_advise_black = global::Skobbler.SDKDemo.Resource.Drawable.ic_destination_advise_black;
			global::Skobbler.SDKTools.Resource.Drawable.ic_destination_advise_white = global::Skobbler.SDKDemo.Resource.Drawable.ic_destination_advise_white;
			global::Skobbler.SDKTools.Resource.Drawable.ic_launcher = global::Skobbler.SDKDemo.Resource.Drawable.ic_launcher;
			global::Skobbler.SDKTools.Resource.Drawable.ic_nav_arrow = global::Skobbler.SDKDemo.Resource.Drawable.ic_nav_arrow;
			global::Skobbler.SDKTools.Resource.Drawable.ic_nightmode = global::Skobbler.SDKDemo.Resource.Drawable.ic_nightmode;
			global::Skobbler.SDKTools.Resource.Drawable.ic_no_gps = global::Skobbler.SDKDemo.Resource.Drawable.ic_no_gps;
			global::Skobbler.SDKTools.Resource.Drawable.ic_overview = global::Skobbler.SDKDemo.Resource.Drawable.ic_overview;
			global::Skobbler.SDKTools.Resource.Drawable.ic_panning = global::Skobbler.SDKDemo.Resource.Drawable.ic_panning;
			global::Skobbler.SDKTools.Resource.Drawable.ic_quit = global::Skobbler.SDKDemo.Resource.Drawable.ic_quit;
			global::Skobbler.SDKTools.Resource.Drawable.ic_roadblock = global::Skobbler.SDKDemo.Resource.Drawable.ic_roadblock;
			global::Skobbler.SDKTools.Resource.Drawable.ic_roadblock_inact = global::Skobbler.SDKDemo.Resource.Drawable.ic_roadblock_inact;
			global::Skobbler.SDKTools.Resource.Drawable.ic_routeinfo = global::Skobbler.SDKDemo.Resource.Drawable.ic_routeinfo;
			global::Skobbler.SDKTools.Resource.Drawable.ic_zoom_in = global::Skobbler.SDKDemo.Resource.Drawable.ic_zoom_in;
			global::Skobbler.SDKTools.Resource.Drawable.ic_zoom_out = global::Skobbler.SDKDemo.Resource.Drawable.ic_zoom_out;
			global::Skobbler.SDKTools.Resource.Drawable.icon_arrow_list = global::Skobbler.SDKDemo.Resource.Drawable.icon_arrow_list;
			global::Skobbler.SDKTools.Resource.Drawable.icon_position_me = global::Skobbler.SDKDemo.Resource.Drawable.icon_position_me;
			global::Skobbler.SDKTools.Resource.Drawable.scrubber_control_disabled_holo = global::Skobbler.SDKDemo.Resource.Drawable.scrubber_control_disabled_holo;
			global::Skobbler.SDKTools.Resource.Drawable.scrubber_control_focused_holo = global::Skobbler.SDKDemo.Resource.Drawable.scrubber_control_focused_holo;
			global::Skobbler.SDKTools.Resource.Drawable.scrubber_control_normal_holo = global::Skobbler.SDKDemo.Resource.Drawable.scrubber_control_normal_holo;
			global::Skobbler.SDKTools.Resource.Drawable.scrubber_control_pressed_holo = global::Skobbler.SDKDemo.Resource.Drawable.scrubber_control_pressed_holo;
			global::Skobbler.SDKTools.Resource.Drawable.scrubber_primary_holo = global::Skobbler.SDKDemo.Resource.Drawable.scrubber_primary_holo;
			global::Skobbler.SDKTools.Resource.Drawable.scrubber_secondary_holo = global::Skobbler.SDKDemo.Resource.Drawable.scrubber_secondary_holo;
			global::Skobbler.SDKTools.Resource.Drawable.scrubber_track_holo_dark = global::Skobbler.SDKDemo.Resource.Drawable.scrubber_track_holo_dark;
			global::Skobbler.SDKTools.Resource.Drawable.volume_seekbar = global::Skobbler.SDKDemo.Resource.Drawable.volume_seekbar;
			global::Skobbler.SDKTools.Resource.Drawable.volume_thumb_selector = global::Skobbler.SDKDemo.Resource.Drawable.volume_thumb_selector;
			global::Skobbler.SDKTools.Resource.Id.alternative_routes_layout = global::Skobbler.SDKDemo.Resource.Id.alternative_routes_layout;
			global::Skobbler.SDKTools.Resource.Id.arriving_distance_text = global::Skobbler.SDKDemo.Resource.Id.arriving_distance_text;
			global::Skobbler.SDKTools.Resource.Id.arriving_distance_text_value = global::Skobbler.SDKDemo.Resource.Id.arriving_distance_text_value;
			global::Skobbler.SDKTools.Resource.Id.arriving_time_text = global::Skobbler.SDKDemo.Resource.Id.arriving_time_text;
			global::Skobbler.SDKTools.Resource.Id.arriving_time_text_ampm = global::Skobbler.SDKDemo.Resource.Id.arriving_time_text_ampm;
			global::Skobbler.SDKTools.Resource.Id.cancel_pre_navigation_button = global::Skobbler.SDKDemo.Resource.Id.cancel_pre_navigation_button;
			global::Skobbler.SDKTools.Resource.Id.current_advice_distance_text = global::Skobbler.SDKDemo.Resource.Id.current_advice_distance_text;
			global::Skobbler.SDKTools.Resource.Id.current_advice_image_holder = global::Skobbler.SDKDemo.Resource.Id.current_advice_image_holder;
			global::Skobbler.SDKTools.Resource.Id.current_advice_image_turn = global::Skobbler.SDKDemo.Resource.Id.current_advice_image_turn;
			global::Skobbler.SDKTools.Resource.Id.current_advice_street_text = global::Skobbler.SDKDemo.Resource.Id.current_advice_street_text;
			global::Skobbler.SDKTools.Resource.Id.current_advice_text_holder = global::Skobbler.SDKDemo.Resource.Id.current_advice_text_holder;
			global::Skobbler.SDKTools.Resource.Id.estimated_navigation_time_text = global::Skobbler.SDKDemo.Resource.Id.estimated_navigation_time_text;
			global::Skobbler.SDKTools.Resource.Id.estimated_navigation_time_text_value = global::Skobbler.SDKDemo.Resource.Id.estimated_navigation_time_text_value;
			global::Skobbler.SDKTools.Resource.Id.first_route = global::Skobbler.SDKDemo.Resource.Id.first_route;
			global::Skobbler.SDKTools.Resource.Id.free_drive_current_speed_linear_layout = global::Skobbler.SDKDemo.Resource.Id.free_drive_current_speed_linear_layout;
			global::Skobbler.SDKTools.Resource.Id.free_drive_current_speed_text = global::Skobbler.SDKDemo.Resource.Id.free_drive_current_speed_text;
			global::Skobbler.SDKTools.Resource.Id.free_drive_current_speed_text_value = global::Skobbler.SDKDemo.Resource.Id.free_drive_current_speed_text_value;
			global::Skobbler.SDKTools.Resource.Id.free_drive_current_street_text = global::Skobbler.SDKDemo.Resource.Id.free_drive_current_street_text;
			global::Skobbler.SDKTools.Resource.Id.increase_decrease_layout = global::Skobbler.SDKDemo.Resource.Id.increase_decrease_layout;
			global::Skobbler.SDKTools.Resource.Id.menu_back_follower_mode_button = global::Skobbler.SDKDemo.Resource.Id.menu_back_follower_mode_button;
			global::Skobbler.SDKTools.Resource.Id.menu_back_prenavigation_button = global::Skobbler.SDKDemo.Resource.Id.menu_back_prenavigation_button;
			global::Skobbler.SDKTools.Resource.Id.nav_settings_first_row = global::Skobbler.SDKDemo.Resource.Id.nav_settings_first_row;
			global::Skobbler.SDKTools.Resource.Id.nav_settings_forth_row = global::Skobbler.SDKDemo.Resource.Id.nav_settings_forth_row;
			global::Skobbler.SDKTools.Resource.Id.nav_settings_second_row = global::Skobbler.SDKDemo.Resource.Id.nav_settings_second_row;
			global::Skobbler.SDKTools.Resource.Id.nav_settings_third_row = global::Skobbler.SDKDemo.Resource.Id.nav_settings_third_row;
			global::Skobbler.SDKTools.Resource.Id.navigation_alert_sign_image = global::Skobbler.SDKDemo.Resource.Id.navigation_alert_sign_image;
			global::Skobbler.SDKTools.Resource.Id.navigation_bottom_right_arriving_panel = global::Skobbler.SDKDemo.Resource.Id.navigation_bottom_right_arriving_panel;
			global::Skobbler.SDKTools.Resource.Id.navigation_bottom_right_estimated_panel = global::Skobbler.SDKDemo.Resource.Id.navigation_bottom_right_estimated_panel;
			global::Skobbler.SDKTools.Resource.Id.navigation_contribute_option_text = global::Skobbler.SDKDemo.Resource.Id.navigation_contribute_option_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_decrease_speed = global::Skobbler.SDKDemo.Resource.Id.navigation_decrease_speed;
			global::Skobbler.SDKTools.Resource.Id.navigation_free_drive_speed_limit_panel = global::Skobbler.SDKDemo.Resource.Id.navigation_free_drive_speed_limit_panel;
			global::Skobbler.SDKTools.Resource.Id.navigation_increase_speed = global::Skobbler.SDKDemo.Resource.Id.navigation_increase_speed;
			global::Skobbler.SDKTools.Resource.Id.navigation_next_advice_image_distance_overlay_background = global::Skobbler.SDKDemo.Resource.Id.navigation_next_advice_image_distance_overlay_background;
			global::Skobbler.SDKTools.Resource.Id.navigation_next_advice_street_overlay_background = global::Skobbler.SDKDemo.Resource.Id.navigation_next_advice_street_overlay_background;
			global::Skobbler.SDKTools.Resource.Id.navigation_route_overview_current_position_label = global::Skobbler.SDKDemo.Resource.Id.navigation_route_overview_current_position_label;
			global::Skobbler.SDKTools.Resource.Id.navigation_route_overview_current_position_text = global::Skobbler.SDKDemo.Resource.Id.navigation_route_overview_current_position_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_route_overview_destination_label = global::Skobbler.SDKDemo.Resource.Id.navigation_route_overview_destination_label;
			global::Skobbler.SDKTools.Resource.Id.navigation_route_overview_destination_layout = global::Skobbler.SDKDemo.Resource.Id.navigation_route_overview_destination_layout;
			global::Skobbler.SDKTools.Resource.Id.navigation_route_overview_destination_text = global::Skobbler.SDKDemo.Resource.Id.navigation_route_overview_destination_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_route_overview_linear_layout = global::Skobbler.SDKDemo.Resource.Id.navigation_route_overview_linear_layout;
			global::Skobbler.SDKTools.Resource.Id.navigation_route_overview_starting_position_layout = global::Skobbler.SDKDemo.Resource.Id.navigation_route_overview_starting_position_layout;
			global::Skobbler.SDKTools.Resource.Id.navigation_searching_for_gps_text = global::Skobbler.SDKDemo.Resource.Id.navigation_searching_for_gps_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_audio_button = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_audio_button;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_audio_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_audio_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_back_button = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_back_button;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_day_night_mode_button = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_day_night_mode_button;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_day_night_mode_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_day_night_mode_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_option_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_option_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_overview_button = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_overview_button;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_overview_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_overview_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_panning_button = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_panning_button;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_panning_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_panning_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_quit_button = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_quit_button;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_quit_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_quit_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_roadblock_info_button = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_roadblock_info_button;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_roadblock_info_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_roadblock_info_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_route_info_button = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_route_info_button;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_route_info_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_route_info_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_seek_bar_layout = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_seek_bar_layout;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_view_mode_button = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_view_mode_button;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_view_mode_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_view_mode_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_volume = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_volume;
			global::Skobbler.SDKTools.Resource.Id.navigation_settings_volume_text = global::Skobbler.SDKDemo.Resource.Id.navigation_settings_volume_text;
			global::Skobbler.SDKTools.Resource.Id.navigation_speed_sign_image = global::Skobbler.SDKDemo.Resource.Id.navigation_speed_sign_image;
			global::Skobbler.SDKTools.Resource.Id.navigation_top_back_button = global::Skobbler.SDKDemo.Resource.Id.navigation_top_back_button;
			global::Skobbler.SDKTools.Resource.Id.next_advice_distance_text = global::Skobbler.SDKDemo.Resource.Id.next_advice_distance_text;
			global::Skobbler.SDKTools.Resource.Id.next_advice_street_name_text = global::Skobbler.SDKDemo.Resource.Id.next_advice_street_name_text;
			global::Skobbler.SDKTools.Resource.Id.next_advice_street_name_text_layout = global::Skobbler.SDKDemo.Resource.Id.next_advice_street_name_text_layout;
			global::Skobbler.SDKTools.Resource.Id.next_image_turn_advice = global::Skobbler.SDKDemo.Resource.Id.next_image_turn_advice;
			global::Skobbler.SDKTools.Resource.Id.next_image_turn_advice_distance_layout = global::Skobbler.SDKDemo.Resource.Id.next_image_turn_advice_distance_layout;
			global::Skobbler.SDKTools.Resource.Id.position_me_real_navigation_button = global::Skobbler.SDKDemo.Resource.Id.position_me_real_navigation_button;
			global::Skobbler.SDKTools.Resource.Id.re_routing_text = global::Skobbler.SDKDemo.Resource.Id.re_routing_text;
			global::Skobbler.SDKTools.Resource.Id.road_block_relative_layout = global::Skobbler.SDKDemo.Resource.Id.road_block_relative_layout;
			global::Skobbler.SDKTools.Resource.Id.roadblock_list = global::Skobbler.SDKDemo.Resource.Id.roadblock_list;
			global::Skobbler.SDKTools.Resource.Id.route_distance_linear_layout = global::Skobbler.SDKDemo.Resource.Id.route_distance_linear_layout;
			global::Skobbler.SDKTools.Resource.Id.second_route = global::Skobbler.SDKDemo.Resource.Id.second_route;
			global::Skobbler.SDKTools.Resource.Id.speed_limit_value = global::Skobbler.SDKDemo.Resource.Id.speed_limit_value;
			global::Skobbler.SDKTools.Resource.Id.start_navigation_button = global::Skobbler.SDKDemo.Resource.Id.start_navigation_button;
			global::Skobbler.SDKTools.Resource.Id.third_route = global::Skobbler.SDKDemo.Resource.Id.third_route;
			global::Skobbler.SDKTools.Resource.Id.via_point_text_view = global::Skobbler.SDKDemo.Resource.Id.via_point_text_view;
			global::Skobbler.SDKTools.Resource.Layout.element_free_drive_current_street_panel = global::Skobbler.SDKDemo.Resource.Layout.element_free_drive_current_street_panel;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_back_button = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_back_button;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_bottom_right_arriving_panel = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_bottom_right_arriving_panel;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_bottom_right_estimated_panel = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_bottom_right_estimated_panel;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_current_advice_panel = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_current_advice_panel;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_eta_arriving_group_panels = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_eta_arriving_group_panels;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_menu_options = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_menu_options;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_next_advice_panel = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_next_advice_panel;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_rerouting_panel = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_rerouting_panel;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_roadblocks_list = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_roadblocks_list;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_route_distance = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_route_distance;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_route_overview_panel = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_route_overview_panel;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_searching_for_gps = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_searching_for_gps;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_settings = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_settings;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_simulation_buttons = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_simulation_buttons;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_speed_panel = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_speed_panel;
			global::Skobbler.SDKTools.Resource.Layout.element_navigation_via_point_panel = global::Skobbler.SDKDemo.Resource.Layout.element_navigation_via_point_panel;
			global::Skobbler.SDKTools.Resource.Layout.element_position_me_button = global::Skobbler.SDKDemo.Resource.Layout.element_position_me_button;
			global::Skobbler.SDKTools.Resource.Layout.element_pre_navigation_buttons_panel = global::Skobbler.SDKDemo.Resource.Layout.element_pre_navigation_buttons_panel;
			global::Skobbler.SDKTools.Resource.String.cancel_label = global::Skobbler.SDKDemo.Resource.String.cancel_label;
			global::Skobbler.SDKTools.Resource.String.current_position = global::Skobbler.SDKDemo.Resource.String.current_position;
			global::Skobbler.SDKTools.Resource.String.decrease_speed = global::Skobbler.SDKDemo.Resource.String.decrease_speed;
			global::Skobbler.SDKTools.Resource.String.destination_label = global::Skobbler.SDKDemo.Resource.String.destination_label;
			global::Skobbler.SDKTools.Resource.String.destination_reached_info_text = global::Skobbler.SDKDemo.Resource.String.destination_reached_info_text;
			global::Skobbler.SDKTools.Resource.String.distance_time = global::Skobbler.SDKDemo.Resource.String.distance_time;
			global::Skobbler.SDKTools.Resource.String.download_cancel = global::Skobbler.SDKDemo.Resource.String.download_cancel;
			global::Skobbler.SDKTools.Resource.String.download_pause = global::Skobbler.SDKDemo.Resource.String.download_pause;
			global::Skobbler.SDKTools.Resource.String.download_resume = global::Skobbler.SDKDemo.Resource.String.download_resume;
			global::Skobbler.SDKTools.Resource.String.download_start = global::Skobbler.SDKDemo.Resource.String.download_start;
			global::Skobbler.SDKTools.Resource.String.exit_highway_advice_label = global::Skobbler.SDKDemo.Resource.String.exit_highway_advice_label;
			global::Skobbler.SDKTools.Resource.String.exit_navigation_dialog_message = global::Skobbler.SDKDemo.Resource.String.exit_navigation_dialog_message;
			global::Skobbler.SDKTools.Resource.String.exit_navigation_dialog_title = global::Skobbler.SDKDemo.Resource.String.exit_navigation_dialog_title;
			global::Skobbler.SDKTools.Resource.String.feet_label = global::Skobbler.SDKDemo.Resource.String.feet_label;
			global::Skobbler.SDKTools.Resource.String.hour_value = global::Skobbler.SDKDemo.Resource.String.hour_value;
			global::Skobbler.SDKTools.Resource.String.increase_speed = global::Skobbler.SDKDemo.Resource.String.increase_speed;
			global::Skobbler.SDKTools.Resource.String.km_label = global::Skobbler.SDKDemo.Resource.String.km_label;
			global::Skobbler.SDKTools.Resource.String.kmh_label = global::Skobbler.SDKDemo.Resource.String.kmh_label;
			global::Skobbler.SDKTools.Resource.String.less = global::Skobbler.SDKDemo.Resource.String.less;
			global::Skobbler.SDKTools.Resource.String.meters_label = global::Skobbler.SDKDemo.Resource.String.meters_label;
			global::Skobbler.SDKTools.Resource.String.mi_label = global::Skobbler.SDKDemo.Resource.String.mi_label;
			global::Skobbler.SDKTools.Resource.String.minute_value = global::Skobbler.SDKDemo.Resource.String.minute_value;
			global::Skobbler.SDKTools.Resource.String.more = global::Skobbler.SDKDemo.Resource.String.more;
			global::Skobbler.SDKTools.Resource.String.mph_label = global::Skobbler.SDKDemo.Resource.String.mph_label;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_2d_view = global::Skobbler.SDKDemo.Resource.String.navigate_settings_2d_view;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_3d_view = global::Skobbler.SDKDemo.Resource.String.navigate_settings_3d_view;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_audio_off = global::Skobbler.SDKDemo.Resource.String.navigate_settings_audio_off;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_audio_on = global::Skobbler.SDKDemo.Resource.String.navigate_settings_audio_on;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_block_road = global::Skobbler.SDKDemo.Resource.String.navigate_settings_block_road;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_daymode = global::Skobbler.SDKDemo.Resource.String.navigate_settings_daymode;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_nightmode = global::Skobbler.SDKDemo.Resource.String.navigate_settings_nightmode;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_overview = global::Skobbler.SDKDemo.Resource.String.navigate_settings_overview;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_panning = global::Skobbler.SDKDemo.Resource.String.navigate_settings_panning;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_quit = global::Skobbler.SDKDemo.Resource.String.navigate_settings_quit;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_reload = global::Skobbler.SDKDemo.Resource.String.navigate_settings_reload;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_routeinfo = global::Skobbler.SDKDemo.Resource.String.navigate_settings_routeinfo;
			global::Skobbler.SDKTools.Resource.String.navigate_settings_volume = global::Skobbler.SDKDemo.Resource.String.navigate_settings_volume;
			global::Skobbler.SDKTools.Resource.String.no_position_available = global::Skobbler.SDKDemo.Resource.String.no_position_available;
			global::Skobbler.SDKTools.Resource.String.ok_label = global::Skobbler.SDKDemo.Resource.String.ok_label;
			global::Skobbler.SDKTools.Resource.String.quit_navigation = global::Skobbler.SDKDemo.Resource.String.quit_navigation;
			global::Skobbler.SDKTools.Resource.String.re_routing = global::Skobbler.SDKDemo.Resource.String.re_routing;
			global::Skobbler.SDKTools.Resource.String.route_cannot_be_calculated = global::Skobbler.SDKDemo.Resource.String.route_cannot_be_calculated;
			global::Skobbler.SDKTools.Resource.String.route_invalid_destination = global::Skobbler.SDKDemo.Resource.String.route_invalid_destination;
			global::Skobbler.SDKTools.Resource.String.route_invalid_start = global::Skobbler.SDKDemo.Resource.String.route_invalid_start;
			global::Skobbler.SDKTools.Resource.String.route_same_start_and_destination = global::Skobbler.SDKDemo.Resource.String.route_same_start_and_destination;
			global::Skobbler.SDKTools.Resource.String.route_unknown_server_error = global::Skobbler.SDKDemo.Resource.String.route_unknown_server_error;
			global::Skobbler.SDKTools.Resource.String.routing_server_error = global::Skobbler.SDKDemo.Resource.String.routing_server_error;
			global::Skobbler.SDKTools.Resource.String.searching_for_gps_label = global::Skobbler.SDKDemo.Resource.String.searching_for_gps_label;
			global::Skobbler.SDKTools.Resource.String.seconds_value = global::Skobbler.SDKDemo.Resource.String.seconds_value;
			global::Skobbler.SDKTools.Resource.String.settings_label = global::Skobbler.SDKDemo.Resource.String.settings_label;
			global::Skobbler.SDKTools.Resource.String.start_prim_navigation = global::Skobbler.SDKDemo.Resource.String.start_prim_navigation;
			global::Skobbler.SDKTools.Resource.String.starting_pos_label = global::Skobbler.SDKDemo.Resource.String.starting_pos_label;
			global::Skobbler.SDKTools.Resource.String.unblock_all = global::Skobbler.SDKDemo.Resource.String.unblock_all;
			global::Skobbler.SDKTools.Resource.String.via_point_reached = global::Skobbler.SDKDemo.Resource.String.via_point_reached;
			global::Skobbler.SDKTools.Resource.String.yards_label = global::Skobbler.SDKDemo.Resource.String.yards_label;
			global::Skobbler.SDKTools.Resource.Style.alternate_route_cell_style = global::Skobbler.SDKDemo.Resource.Style.alternate_route_cell_style;
			global::Skobbler.SDKTools.Resource.Style.alternate_route_cell_style_landscape = global::Skobbler.SDKDemo.Resource.Style.alternate_route_cell_style_landscape;
			global::Skobbler.SDKTools.Resource.Style.alternate_route_text_holder_style = global::Skobbler.SDKDemo.Resource.Style.alternate_route_text_holder_style;
			global::Skobbler.SDKTools.Resource.Style.alternate_route_text_style_normal = global::Skobbler.SDKDemo.Resource.Style.alternate_route_text_style_normal;
			global::Skobbler.SDKTools.Resource.Style.alternate_route_text_style_tvdpi = global::Skobbler.SDKDemo.Resource.Style.alternate_route_text_style_tvdpi;
			global::Skobbler.SDKTools.Resource.Style.general_black_button_label_normal_screen = global::Skobbler.SDKDemo.Resource.Style.general_black_button_label_normal_screen;
			global::Skobbler.SDKTools.Resource.Style.general_white_button_label = global::Skobbler.SDKDemo.Resource.Style.general_white_button_label;
			global::Skobbler.SDKTools.Resource.Style.general_white_button_label_normal_screen = global::Skobbler.SDKDemo.Resource.Style.general_white_button_label_normal_screen;
			global::Skobbler.SDKTools.Resource.Style.navigation_settings_layout = global::Skobbler.SDKDemo.Resource.Style.navigation_settings_layout;
			global::Skobbler.SDKTools.Resource.Style.navigation_settings_text = global::Skobbler.SDKDemo.Resource.Style.navigation_settings_text;
			global::Skobbler.SDKTools.Resource.Style.navigation_settings_text_normal = global::Skobbler.SDKDemo.Resource.Style.navigation_settings_text_normal;
			global::Skobbler.SDKTools.Resource.Style.pre_navigation_text = global::Skobbler.SDKDemo.Resource.Style.pre_navigation_text;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060005
			public const int distance_unit = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int distance_unit_values = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int navigation_type = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int navigation_type_value = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int number_routes = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int number_routes_values = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int road_blocks_in_feet = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int road_blocks_in_meters = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int road_blocks_in_yards = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int route_types = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int route_values = 2131099652;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int black = 2131165184;
			
			// aapt resource value: 0x7f070015
			public const int blue_filling = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int blue_outline = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int blue_panel_day_background = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int blue_panel_night_background = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int blue_panel_night_text = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int bullet_gray = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int bullet_green = 2131165189;
			
			// aapt resource value: 0x7f070017
			public const int darker_grey = 2131165207;
			
			// aapt resource value: 0x7f070003
			public const int gray = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int green_panel_day_background = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int green_panel_night_background = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int green_panel_night_text = 2131165198;
			
			// aapt resource value: 0x7f070018
			public const int grey = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int grey_options_group = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int light_orange = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int list_text_color = 2131165213;
			
			// aapt resource value: 0x7f070008
			public const int navigation_next_advice_overlay_background = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int navigation_semitransparent_separator = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int navigation_style_day = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int navigation_style_night = 2131165195;
			
			// aapt resource value: 0x7f07001b
			public const int orange = 2131165211;
			
			// aapt resource value: 0x7f070002
			public const int red = 2131165186;
			
			// aapt resource value: 0x7f07001a
			public const int selected = 2131165210;
			
			// aapt resource value: 0x7f070006
			public const int speed_exceeded = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int speed_panel_night_background = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int white = 2131165185;
			
			// aapt resource value: 0x7f070012
			public const int yellow_panel_day_background = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int yellow_panel_night_background = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int yellow_panel_night_text = 2131165204;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f08000c
			public const int action_bar_size = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int alternate_routes_top_bar_size = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int alternate_routes_total_delay_panel_size = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int map_controls_background_size = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int map_controls_button_size = 2131230736;
			
			// aapt resource value: 0x7f080016
			public const int navigation_bottom_panel_height = 2131230742;
			
			// aapt resource value: 0x7f080009
			public const int navigation_bottom_text_sub_title_size = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int navigation_bottom_text_title_size = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int navigation_current_advice_panel_landscape_height = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int navigation_current_advice_panel_portrait_width = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int navigation_current_image_landscape = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int navigation_current_image_portrait = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int navigation_next_advice_panel_portrait_height = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int navigation_next_image_landscape = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int navigation_next_image_portrait = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int navigation_panel_landscape_height = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int navigation_panel_landscape_width = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int navigation_panel_width_height = 2131230741;
			
			// aapt resource value: 0x7f080004
			public const int navigation_speed_limit_speed_cam = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int promotion_progress_wheel = 2131230733;
			
			// aapt resource value: 0x7f080014
			public const int text_view_large = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int text_view_medium = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int text_view_small = 2131230738;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_right = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_alert_sign = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_alert_sign_us = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background_speed_sign = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background_speed_sign_us = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bullet_gray = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bullet_green = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_background_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_selector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cancel = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dot_full = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int download = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_2d = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_3d = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_alert_exclamationmark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_audio_off = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_audio_on = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_back_arrow = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_contribute = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_daymode = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_destination_advise_black = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_destination_advise_white = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_launcher = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_nav_arrow = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_nightmode = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_no_gps = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_overview = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_panning = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_quit = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_roadblock = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_roadblock_inact = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_routeinfo = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_zoom_in = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_zoom_out = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int icon_arrow_list = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int icon_dropdownmenu_bike = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int icon_dropdownmenu_car = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int icon_dropdownmenu_pedestrian = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int icon_map_popup_navigate = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon_position_me = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int icon_searchcenter_favorite = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int list_item_selector = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int logo_skobbler_by_scout = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int map_background = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int menu_options_selector = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int option_background = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int pause = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int play = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int rounded_corners = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int scrubber_control_disabled_holo = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int scrubber_control_focused_holo = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int scrubber_control_normal_holo = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int scrubber_control_pressed_holo = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int scrubber_primary_holo = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int scrubber_secondary_holo = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int scrubber_track_holo_dark = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int splashscreen_background = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int texture_map_unavailable = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int volume_seekbar = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int volume_thumb_selector = 2130837564;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0092
			public const int alt_route_1 = 2131427474;
			
			// aapt resource value: 0x7f0b0093
			public const int alt_route_2 = 2131427475;
			
			// aapt resource value: 0x7f0b0094
			public const int alt_route_3 = 2131427476;
			
			// aapt resource value: 0x7f0b000e
			public const int alt_routes = 2131427342;
			
			// aapt resource value: 0x7f0b007e
			public const int alternative_routes_layout = 2131427454;
			
			// aapt resource value: 0x7f0b0091
			public const int alternative_routes_layout_traffic = 2131427473;
			
			// aapt resource value: 0x7f0b004f
			public const int arriving_distance_text = 2131427407;
			
			// aapt resource value: 0x7f0b0050
			public const int arriving_distance_text_value = 2131427408;
			
			// aapt resource value: 0x7f0b0037
			public const int arriving_time_text = 2131427383;
			
			// aapt resource value: 0x7f0b0038
			public const int arriving_time_text_ampm = 2131427384;
			
			// aapt resource value: 0x7f0b0027
			public const int arrow = 2131427367;
			
			// aapt resource value: 0x7f0b0011
			public const int bottom_button = 2131427345;
			
			// aapt resource value: 0x7f0b00c6
			public const int bottom_text = 2131427526;
			
			// aapt resource value: 0x7f0b00bf
			public const int calculate_pedestrian_routes_button = 2131427519;
			
			// aapt resource value: 0x7f0b00b7
			public const int calculate_routes_button = 2131427511;
			
			// aapt resource value: 0x7f0b002e
			public const int cancel = 2131427374;
			
			// aapt resource value: 0x7f0b0004
			public const int cancel_all_button = 2131427332;
			
			// aapt resource value: 0x7f0b0084
			public const int cancel_pre_navigation_button = 2131427460;
			
			// aapt resource value: 0x7f0b000a
			public const int chess_board_background = 2131427338;
			
			// aapt resource value: 0x7f0b001e
			public const int chess_table_background = 2131427358;
			
			// aapt resource value: 0x7f0b00b6
			public const int clear_via_point_button = 2131427510;
			
			// aapt resource value: 0x7f0b003e
			public const int current_advice_distance_text = 2131427390;
			
			// aapt resource value: 0x7f0b003b
			public const int current_advice_image_holder = 2131427387;
			
			// aapt resource value: 0x7f0b003c
			public const int current_advice_image_turn = 2131427388;
			
			// aapt resource value: 0x7f0b003f
			public const int current_advice_street_text = 2131427391;
			
			// aapt resource value: 0x7f0b003d
			public const int current_advice_text_holder = 2131427389;
			
			// aapt resource value: 0x7f0b002f
			public const int current_state = 2131427375;
			
			// aapt resource value: 0x7f0b0014
			public const int customView = 2131427348;
			
			// aapt resource value: 0x7f0b0099
			public const int custom_layout = 2131427481;
			
			// aapt resource value: 0x7f0b001f
			public const int details = 2131427359;
			
			// aapt resource value: 0x7f0b0001
			public const int download_button = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int download_percentage_text = 2131427330;
			
			// aapt resource value: 0x7f0b0030
			public const int download_progress = 2131427376;
			
			// aapt resource value: 0x7f0b0000
			public const int download_progress_bar = 2131427328;
			
			// aapt resource value: 0x7f0b00ca
			public const int draw_button = 2131427530;
			
			// aapt resource value: 0x7f0b0039
			public const int estimated_navigation_time_text = 2131427385;
			
			// aapt resource value: 0x7f0b003a
			public const int estimated_navigation_time_text_value = 2131427386;
			
			// aapt resource value: 0x7f0b008c
			public const int exit_real_reach = 2131427468;
			
			// aapt resource value: 0x7f0b008d
			public const int exit_real_reach_energy = 2131427469;
			
			// aapt resource value: 0x7f0b0090
			public const int exit_real_reach_time = 2131427472;
			
			// aapt resource value: 0x7f0b007f
			public const int first_route = 2131427455;
			
			// aapt resource value: 0x7f0b0008
			public const int frameLayout = 2131427336;
			
			// aapt resource value: 0x7f0b0079
			public const int free_drive_current_speed_linear_layout = 2131427449;
			
			// aapt resource value: 0x7f0b007a
			public const int free_drive_current_speed_text = 2131427450;
			
			// aapt resource value: 0x7f0b007b
			public const int free_drive_current_speed_text_value = 2131427451;
			
			// aapt resource value: 0x7f0b0035
			public const int free_drive_current_street_text = 2131427381;
			
			// aapt resource value: 0x7f0b0026
			public const int gpx_chicago = 2131427366;
			
			// aapt resource value: 0x7f0b0022
			public const int gpx_route_1 = 2131427362;
			
			// aapt resource value: 0x7f0b0023
			public const int gpx_route_2 = 2131427363;
			
			// aapt resource value: 0x7f0b0024
			public const int gpx_route_3 = 2131427364;
			
			// aapt resource value: 0x7f0b0025
			public const int gpx_route_4 = 2131427365;
			
			// aapt resource value: 0x7f0b0013
			public const int heading_button = 2131427347;
			
			// aapt resource value: 0x7f0b0072
			public const int increase_decrease_layout = 2131427442;
			
			// aapt resource value: 0x7f0b00c9
			public const int indicator_children_available = 2131427529;
			
			// aapt resource value: 0x7f0b00cb
			public const int label_list_item = 2131427531;
			
			// aapt resource value: 0x7f0b0006
			public const int label_operation_in_progress = 2131427334;
			
			// aapt resource value: 0x7f0b001a
			public const int latitude = 2131427354;
			
			// aapt resource value: 0x7f0b0019
			public const int latitude_field = 2131427353;
			
			// aapt resource value: 0x7f0b00c3
			public const int left_image = 2131427523;
			
			// aapt resource value: 0x7f0b0028
			public const int left_layout = 2131427368;
			
			// aapt resource value: 0x7f0b0085
			public const int linearLayout1 = 2131427461;
			
			// aapt resource value: 0x7f0b0003
			public const int list_view = 2131427331;
			
			// aapt resource value: 0x7f0b001c
			public const int longitude = 2131427356;
			
			// aapt resource value: 0x7f0b001b
			public const int longitude_field = 2131427355;
			
			// aapt resource value: 0x7f0b0007
			public const int map_layout_root = 2131427335;
			
			// aapt resource value: 0x7f0b009a
			public const int map_style_day = 2131427482;
			
			// aapt resource value: 0x7f0b009d
			public const int map_style_grayscale = 2131427485;
			
			// aapt resource value: 0x7f0b009b
			public const int map_style_night = 2131427483;
			
			// aapt resource value: 0x7f0b009c
			public const int map_style_outdoor = 2131427484;
			
			// aapt resource value: 0x7f0b000f
			public const int map_styles = 2131427343;
			
			// aapt resource value: 0x7f0b0071
			public const int menu_back_follower_mode_button = 2131427441;
			
			// aapt resource value: 0x7f0b0083
			public const int menu_back_prenavigation_button = 2131427459;
			
			// aapt resource value: 0x7f0b00c4
			public const int mid_layout = 2131427524;
			
			// aapt resource value: 0x7f0b002c
			public const int middle_layout = 2131427372;
			
			// aapt resource value: 0x7f0b005b
			public const int nav_settings_first_row = 2131427419;
			
			// aapt resource value: 0x7f0b006a
			public const int nav_settings_forth_row = 2131427434;
			
			// aapt resource value: 0x7f0b0060
			public const int nav_settings_second_row = 2131427424;
			
			// aapt resource value: 0x7f0b0065
			public const int nav_settings_third_row = 2131427429;
			
			// aapt resource value: 0x7f0b0077
			public const int navigation_alert_sign_image = 2131427447;
			
			// aapt resource value: 0x7f0b0041
			public const int navigation_bottom_right_arriving_panel = 2131427393;
			
			// aapt resource value: 0x7f0b0040
			public const int navigation_bottom_right_estimated_panel = 2131427392;
			
			// aapt resource value: 0x7f0b0043
			public const int navigation_contribute_option_text = 2131427395;
			
			// aapt resource value: 0x7f0b0074
			public const int navigation_decrease_speed = 2131427444;
			
			// aapt resource value: 0x7f0b0075
			public const int navigation_free_drive_speed_limit_panel = 2131427445;
			
			// aapt resource value: 0x7f0b0073
			public const int navigation_increase_speed = 2131427443;
			
			// aapt resource value: 0x7f0b0047
			public const int navigation_next_advice_image_distance_overlay_background = 2131427399;
			
			// aapt resource value: 0x7f0b004a
			public const int navigation_next_advice_street_overlay_background = 2131427402;
			
			// aapt resource value: 0x7f0b0053
			public const int navigation_route_overview_current_position_label = 2131427411;
			
			// aapt resource value: 0x7f0b0054
			public const int navigation_route_overview_current_position_text = 2131427412;
			
			// aapt resource value: 0x7f0b0056
			public const int navigation_route_overview_destination_label = 2131427414;
			
			// aapt resource value: 0x7f0b0055
			public const int navigation_route_overview_destination_layout = 2131427413;
			
			// aapt resource value: 0x7f0b0057
			public const int navigation_route_overview_destination_text = 2131427415;
			
			// aapt resource value: 0x7f0b0051
			public const int navigation_route_overview_linear_layout = 2131427409;
			
			// aapt resource value: 0x7f0b0052
			public const int navigation_route_overview_starting_position_layout = 2131427410;
			
			// aapt resource value: 0x7f0b0058
			public const int navigation_searching_for_gps_text = 2131427416;
			
			// aapt resource value: 0x7f0b005c
			public const int navigation_settings_audio_button = 2131427420;
			
			// aapt resource value: 0x7f0b005d
			public const int navigation_settings_audio_text = 2131427421;
			
			// aapt resource value: 0x7f0b0059
			public const int navigation_settings_back_button = 2131427417;
			
			// aapt resource value: 0x7f0b005e
			public const int navigation_settings_day_night_mode_button = 2131427422;
			
			// aapt resource value: 0x7f0b005f
			public const int navigation_settings_day_night_mode_text = 2131427423;
			
			// aapt resource value: 0x7f0b0042
			public const int navigation_settings_option_text = 2131427394;
			
			// aapt resource value: 0x7f0b0061
			public const int navigation_settings_overview_button = 2131427425;
			
			// aapt resource value: 0x7f0b0062
			public const int navigation_settings_overview_text = 2131427426;
			
			// aapt resource value: 0x7f0b0068
			public const int navigation_settings_panning_button = 2131427432;
			
			// aapt resource value: 0x7f0b0069
			public const int navigation_settings_panning_text = 2131427433;
			
			// aapt resource value: 0x7f0b006d
			public const int navigation_settings_quit_button = 2131427437;
			
			// aapt resource value: 0x7f0b006e
			public const int navigation_settings_quit_text = 2131427438;
			
			// aapt resource value: 0x7f0b0066
			public const int navigation_settings_roadblock_info_button = 2131427430;
			
			// aapt resource value: 0x7f0b0067
			public const int navigation_settings_roadblock_info_text = 2131427431;
			
			// aapt resource value: 0x7f0b0063
			public const int navigation_settings_route_info_button = 2131427427;
			
			// aapt resource value: 0x7f0b0064
			public const int navigation_settings_route_info_text = 2131427428;
			
			// aapt resource value: 0x7f0b005a
			public const int navigation_settings_seek_bar_layout = 2131427418;
			
			// aapt resource value: 0x7f0b006b
			public const int navigation_settings_view_mode_button = 2131427435;
			
			// aapt resource value: 0x7f0b006c
			public const int navigation_settings_view_mode_text = 2131427436;
			
			// aapt resource value: 0x7f0b006f
			public const int navigation_settings_volume = 2131427439;
			
			// aapt resource value: 0x7f0b0070
			public const int navigation_settings_volume_text = 2131427440;
			
			// aapt resource value: 0x7f0b0076
			public const int navigation_speed_sign_image = 2131427446;
			
			// aapt resource value: 0x7f0b0036
			public const int navigation_top_back_button = 2131427382;
			
			// aapt resource value: 0x7f0b00b1
			public const int navigation_ui_back_button = 2131427505;
			
			// aapt resource value: 0x7f0b00b2
			public const int navigation_ui_buttons = 2131427506;
			
			// aapt resource value: 0x7f0b0010
			public const int navigation_ui_layout = 2131427344;
			
			// aapt resource value: 0x7f0b0046
			public const int next_advice_distance_text = 2131427398;
			
			// aapt resource value: 0x7f0b0049
			public const int next_advice_street_name_text = 2131427401;
			
			// aapt resource value: 0x7f0b0048
			public const int next_advice_street_name_text_layout = 2131427400;
			
			// aapt resource value: 0x7f0b0045
			public const int next_image_turn_advice = 2131427397;
			
			// aapt resource value: 0x7f0b0044
			public const int next_image_turn_advice_distance_layout = 2131427396;
			
			// aapt resource value: 0x7f0b00ad
			public const int option_address_search = 2131427501;
			
			// aapt resource value: 0x7f0b00a8
			public const int option_alt_routes = 2131427496;
			
			// aapt resource value: 0x7f0b00a3
			public const int option_annotations = 2131427491;
			
			// aapt resource value: 0x7f0b00af
			public const int option_category_search = 2131427503;
			
			// aapt resource value: 0x7f0b00a0
			public const int option_heat_map = 2131427488;
			
			// aapt resource value: 0x7f0b00a1
			public const int option_map_creator = 2131427489;
			
			// aapt resource value: 0x7f0b009e
			public const int option_map_display = 2131427486;
			
			// aapt resource value: 0x7f0b00a4
			public const int option_map_interaction = 2131427492;
			
			// aapt resource value: 0x7f0b009f
			public const int option_map_styles = 2131427487;
			
			// aapt resource value: 0x7f0b00a6
			public const int option_map_updates = 2131427494;
			
			// aapt resource value: 0x7f0b00a5
			public const int option_map_xml_and_downloads = 2131427493;
			
			// aapt resource value: 0x7f0b00ac
			public const int option_navigation_ui = 2131427500;
			
			// aapt resource value: 0x7f0b00ae
			public const int option_nearby_search = 2131427502;
			
			// aapt resource value: 0x7f0b00a2
			public const int option_overlays = 2131427490;
			
			// aapt resource value: 0x7f0b00ab
			public const int option_poi_tracking = 2131427499;
			
			// aapt resource value: 0x7f0b00a9
			public const int option_real_reach = 2131427497;
			
			// aapt resource value: 0x7f0b00b0
			public const int option_reverse_geocoding = 2131427504;
			
			// aapt resource value: 0x7f0b00a7
			public const int option_routing_and_navigation = 2131427495;
			
			// aapt resource value: 0x7f0b00aa
			public const int option_tracks = 2131427498;
			
			// aapt resource value: 0x7f0b000d
			public const int options_menu = 2131427341;
			
			// aapt resource value: 0x7f0b002b
			public const int package_name = 2131427371;
			
			// aapt resource value: 0x7f0b002a
			public const int package_size = 2131427370;
			
			// aapt resource value: 0x7f0b00bb
			public const int pedestrian_navigation_ui_back_button = 2131427515;
			
			// aapt resource value: 0x7f0b00bc
			public const int pedestrian_navigation_ui_buttons = 2131427516;
			
			// aapt resource value: 0x7f0b0032
			public const int percentage = 2131427378;
			
			// aapt resource value: 0x7f0b00c2
			public const int popup_layout = 2131427522;
			
			// aapt resource value: 0x7f0b0012
			public const int position_me_button = 2131427346;
			
			// aapt resource value: 0x7f0b00ba
			public const int position_me_navigation_ui_button = 2131427514;
			
			// aapt resource value: 0x7f0b00c1
			public const int position_me_pedestrian_navigation_ui_button = 2131427521;
			
			// aapt resource value: 0x7f0b007d
			public const int position_me_real_navigation_button = 2131427453;
			
			// aapt resource value: 0x7f0b0031
			public const int progress_details = 2131427377;
			
			// aapt resource value: 0x7f0b0016
			public const int radius = 2131427350;
			
			// aapt resource value: 0x7f0b0015
			public const int radius_field = 2131427349;
			
			// aapt resource value: 0x7f0b004b
			public const int re_routing_text = 2131427403;
			
			// aapt resource value: 0x7f0b008a
			public const int real_reach_bike_button = 2131427466;
			
			// aapt resource value: 0x7f0b008b
			public const int real_reach_car_button = 2131427467;
			
			// aapt resource value: 0x7f0b008f
			public const int real_reach_energy = 2131427471;
			
			// aapt resource value: 0x7f0b000c
			public const int real_reach_energy_layout = 2131427340;
			
			// aapt resource value: 0x7f0b008e
			public const int real_reach_energy_seekbar = 2131427470;
			
			// aapt resource value: 0x7f0b0089
			public const int real_reach_pedestrian_button = 2131427465;
			
			// aapt resource value: 0x7f0b0088
			public const int real_reach_seekbar = 2131427464;
			
			// aapt resource value: 0x7f0b0087
			public const int real_reach_time = 2131427463;
			
			// aapt resource value: 0x7f0b000b
			public const int real_reach_time_layout = 2131427339;
			
			// aapt resource value: 0x7f0b0020
			public const int reverse_geocode_button = 2131427360;
			
			// aapt resource value: 0x7f0b0021
			public const int reverse_geocoding_result = 2131427361;
			
			// aapt resource value: 0x7f0b004c
			public const int road_block_relative_layout = 2131427404;
			
			// aapt resource value: 0x7f0b004d
			public const int roadblock_list = 2131427405;
			
			// aapt resource value: 0x7f0b004e
			public const int route_distance_linear_layout = 2131427406;
			
			// aapt resource value: 0x7f0b0096
			public const int route_info_0 = 2131427478;
			
			// aapt resource value: 0x7f0b0097
			public const int route_info_1 = 2131427479;
			
			// aapt resource value: 0x7f0b0098
			public const int route_info_2 = 2131427480;
			
			// aapt resource value: 0x7f0b0095
			public const int route_info_layout = 2131427477;
			
			// aapt resource value: 0x7f0b001d
			public const int search_button = 2131427357;
			
			// aapt resource value: 0x7f0b0018
			public const int search_topic = 2131427352;
			
			// aapt resource value: 0x7f0b0017
			public const int search_topic_field = 2131427351;
			
			// aapt resource value: 0x7f0b0080
			public const int second_route = 2131427456;
			
			// aapt resource value: 0x7f0b00be
			public const int selec_pedestriant_end_point_button = 2131427518;
			
			// aapt resource value: 0x7f0b00b4
			public const int select_end_point_button = 2131427508;
			
			// aapt resource value: 0x7f0b00bd
			public const int select_pedestrian_start_point_button = 2131427517;
			
			// aapt resource value: 0x7f0b00b3
			public const int select_start_point_button = 2131427507;
			
			// aapt resource value: 0x7f0b00b5
			public const int select_via_point_button = 2131427509;
			
			// aapt resource value: 0x7f0b00b9
			public const int settings_button = 2131427513;
			
			// aapt resource value: 0x7f0b0005
			public const int show_heat_map = 2131427333;
			
			// aapt resource value: 0x7f0b0034
			public const int speed = 2131427380;
			
			// aapt resource value: 0x7f0b0078
			public const int speed_limit_value = 2131427448;
			
			// aapt resource value: 0x7f0b00b8
			public const int start_free_drive_button = 2131427512;
			
			// aapt resource value: 0x7f0b00c0
			public const int start_free_walk_button = 2131427520;
			
			// aapt resource value: 0x7f0b0082
			public const int start_navigation_button = 2131427458;
			
			// aapt resource value: 0x7f0b002d
			public const int start_pause = 2131427373;
			
			// aapt resource value: 0x7f0b00c8
			public const int subtitle = 2131427528;
			
			// aapt resource value: 0x7f0b0081
			public const int third_route = 2131427457;
			
			// aapt resource value: 0x7f0b0086
			public const int time_label = 2131427462;
			
			// aapt resource value: 0x7f0b0033
			public const int time_left = 2131427379;
			
			// aapt resource value: 0x7f0b00c7
			public const int title = 2131427527;
			
			// aapt resource value: 0x7f0b0029
			public const int top_layout = 2131427369;
			
			// aapt resource value: 0x7f0b00c5
			public const int top_text = 2131427525;
			
			// aapt resource value: 0x7f0b007c
			public const int via_point_text_view = 2131427452;
			
			// aapt resource value: 0x7f0b0009
			public const int view_group_map = 2131427337;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_download = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_downloads_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_list = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_map = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_nearby_search = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_new_map = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_reverse_geocoding = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_settings = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_splash = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_tracks = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int download_list_activity = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int element_download_list_item = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int element_free_drive_current_street_panel = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int element_navigation_back_button = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int element_navigation_bottom_right_arriving_panel = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int element_navigation_bottom_right_estimated_panel = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int element_navigation_current_advice_panel = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int element_navigation_eta_arriving_group_panels = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int element_navigation_menu_options = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int element_navigation_next_advice_panel = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int element_navigation_rerouting_panel = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int element_navigation_roadblocks_list = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int element_navigation_route_distance = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int element_navigation_route_overview_panel = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int element_navigation_searching_for_gps = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int element_navigation_settings = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int element_navigation_simulation_buttons = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int element_navigation_speed_panel = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int element_navigation_via_point_panel = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int element_position_me_button = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int element_pre_navigation_buttons_panel = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int element_real_reach = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int element_real_reach_energy = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int element_real_reach_time = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int layout_alternative_routes = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int layout_custom_view = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int layout_map_styles = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int layout_menu = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int layout_navigation_ui = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int layout_pedestrian_navigation = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int layout_popup = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int layout_search_list_item = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int layout_track_element_list_item = 2130903082;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int maps = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090037
			public const int app_name = 2131296311;
			
			// aapt resource value: 0x7f090062
			public const int calculate_route = 2131296354;
			
			// aapt resource value: 0x7f090075
			public const int calculate_routes = 2131296373;
			
			// aapt resource value: 0x7f09007f
			public const int cancel_all_downloads = 2131296383;
			
			// aapt resource value: 0x7f090000
			public const int cancel_label = 2131296256;
			
			// aapt resource value: 0x7f09005b
			public const int city = 2131296347;
			
			// aapt resource value: 0x7f09007d
			public const int clear_via_point = 2131296381;
			
			// aapt resource value: 0x7f09005a
			public const int country_code = 2131296346;
			
			// aapt resource value: 0x7f09002d
			public const int current_position = 2131296301;
			
			// aapt resource value: 0x7f090014
			public const int decrease_speed = 2131296276;
			
			// aapt resource value: 0x7f09000d
			public const int destination_label = 2131296269;
			
			// aapt resource value: 0x7f090018
			public const int destination_reached_info_text = 2131296280;
			
			// aapt resource value: 0x7f090030
			public const int distance_time = 2131296304;
			
			// aapt resource value: 0x7f090034
			public const int download_cancel = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int download_pause = 2131296309;
			
			// aapt resource value: 0x7f090036
			public const int download_resume = 2131296310;
			
			// aapt resource value: 0x7f090033
			public const int download_start = 2131296307;
			
			// aapt resource value: 0x7f090074
			public const int end_point_nav = 2131296372;
			
			// aapt resource value: 0x7f09000c
			public const int exit_highway_advice_label = 2131296268;
			
			// aapt resource value: 0x7f090016
			public const int exit_navigation_dialog_message = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int exit_navigation_dialog_title = 2131296279;
			
			// aapt resource value: 0x7f090009
			public const int feet_label = 2131296265;
			
			// aapt resource value: 0x7f090093
			public const int fifteen = 2131296403;
			
			// aapt resource value: 0x7f090097
			public const int fifteen_mi_h = 2131296407;
			
			// aapt resource value: 0x7f090091
			public const int five = 2131296401;
			
			// aapt resource value: 0x7f090095
			public const int five_mi_h = 2131296405;
			
			// aapt resource value: 0x7f090080
			public const int general_label = 2131296384;
			
			// aapt resource value: 0x7f09006b
			public const int gpx_license_notification_text = 2131296363;
			
			// aapt resource value: 0x7f09006e
			public const int gpx_route_1 = 2131296366;
			
			// aapt resource value: 0x7f09006f
			public const int gpx_route_2 = 2131296367;
			
			// aapt resource value: 0x7f090070
			public const int gpx_route_3 = 2131296368;
			
			// aapt resource value: 0x7f090071
			public const int gpx_route_4 = 2131296369;
			
			// aapt resource value: 0x7f090072
			public const int gpx_route_5 = 2131296370;
			
			// aapt resource value: 0x7f090002
			public const int hour_value = 2131296258;
			
			// aapt resource value: 0x7f09005d
			public const int house_number = 2131296349;
			
			// aapt resource value: 0x7f090013
			public const int increase_speed = 2131296275;
			
			// aapt resource value: 0x7f09000a
			public const int km_label = 2131296266;
			
			// aapt resource value: 0x7f090088
			public const int km_m = 2131296392;
			
			// aapt resource value: 0x7f090005
			public const int kmh_label = 2131296261;
			
			// aapt resource value: 0x7f090055
			public const int label_download = 2131296341;
			
			// aapt resource value: 0x7f090065
			public const int label_draw = 2131296357;
			
			// aapt resource value: 0x7f090068
			public const int label_heading = 2131296360;
			
			// aapt resource value: 0x7f090054
			public const int label_parsing_xml = 2131296340;
			
			// aapt resource value: 0x7f090067
			public const int label_position_me = 2131296359;
			
			// aapt resource value: 0x7f090066
			public const int label_route = 2131296358;
			
			// aapt resource value: 0x7f090057
			public const int latitude = 2131296343;
			
			// aapt resource value: 0x7f090031
			public const int less = 2131296305;
			
			// aapt resource value: 0x7f09007b
			public const int long_tap_for_position = 2131296379;
			
			// aapt resource value: 0x7f090058
			public const int longitude = 2131296344;
			
			// aapt resource value: 0x7f09004f
			public const int map_style_day = 2131296335;
			
			// aapt resource value: 0x7f090052
			public const int map_style_grayscale = 2131296338;
			
			// aapt resource value: 0x7f090050
			public const int map_style_night = 2131296336;
			
			// aapt resource value: 0x7f090051
			public const int map_style_outdoor = 2131296337;
			
			// aapt resource value: 0x7f090007
			public const int meters_label = 2131296263;
			
			// aapt resource value: 0x7f090089
			public const int mi_feet = 2131296393;
			
			// aapt resource value: 0x7f090008
			public const int mi_label = 2131296264;
			
			// aapt resource value: 0x7f09008a
			public const int mi_yards = 2131296394;
			
			// aapt resource value: 0x7f090003
			public const int minute_value = 2131296259;
			
			// aapt resource value: 0x7f090032
			public const int more = 2131296306;
			
			// aapt resource value: 0x7f090006
			public const int mph_label = 2131296262;
			
			// aapt resource value: 0x7f090053
			public const int navigate = 2131296339;
			
			// aapt resource value: 0x7f090028
			public const int navigate_settings_2d_view = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int navigate_settings_3d_view = 2131296297;
			
			// aapt resource value: 0x7f090021
			public const int navigate_settings_audio_off = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int navigate_settings_audio_on = 2131296290;
			
			// aapt resource value: 0x7f09002c
			public const int navigate_settings_block_road = 2131296300;
			
			// aapt resource value: 0x7f090024
			public const int navigate_settings_daymode = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int navigate_settings_nightmode = 2131296291;
			
			// aapt resource value: 0x7f090020
			public const int navigate_settings_overview = 2131296288;
			
			// aapt resource value: 0x7f090027
			public const int navigate_settings_panning = 2131296295;
			
			// aapt resource value: 0x7f09002b
			public const int navigate_settings_quit = 2131296299;
			
			// aapt resource value: 0x7f090025
			public const int navigate_settings_reload = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int navigate_settings_routeinfo = 2131296294;
			
			// aapt resource value: 0x7f09002a
			public const int navigate_settings_volume = 2131296298;
			
			// aapt resource value: 0x7f090056
			public const int no_internet_connection = 2131296342;
			
			// aapt resource value: 0x7f090019
			public const int no_position_available = 2131296281;
			
			// aapt resource value: 0x7f09007e
			public const int no_position_message = 2131296382;
			
			// aapt resource value: 0x7f09007a
			public const int off_button = 2131296378;
			
			// aapt resource value: 0x7f090001
			public const int ok_label = 2131296257;
			
			// aapt resource value: 0x7f09006c
			public const int ok_text = 2131296364;
			
			// aapt resource value: 0x7f090079
			public const int on_button = 2131296377;
			
			// aapt resource value: 0x7f09008b
			public const int one_route = 2131296395;
			
			// aapt resource value: 0x7f090045
			public const int option_address_search = 2131296325;
			
			// aapt resource value: 0x7f090041
			public const int option_alternative_routes = 2131296321;
			
			// aapt resource value: 0x7f090049
			public const int option_annotations = 2131296329;
			
			// aapt resource value: 0x7f090046
			public const int option_category_search = 2131296326;
			
			// aapt resource value: 0x7f090044
			public const int option_group_searches = 2131296324;
			
			// aapt resource value: 0x7f09004e
			public const int option_heat_map = 2131296334;
			
			// aapt resource value: 0x7f09003b
			public const int option_map_creator = 2131296315;
			
			// aapt resource value: 0x7f090039
			public const int option_map_display = 2131296313;
			
			// aapt resource value: 0x7f09003a
			public const int option_map_styles = 2131296314;
			
			// aapt resource value: 0x7f09003e
			public const int option_map_updates = 2131296318;
			
			// aapt resource value: 0x7f09003d
			public const int option_map_xml_and_downloads = 2131296317;
			
			// aapt resource value: 0x7f09004c
			public const int option_navigation_ui = 2131296332;
			
			// aapt resource value: 0x7f090047
			public const int option_nearby_search = 2131296327;
			
			// aapt resource value: 0x7f09003f
			public const int option_other_map = 2131296319;
			
			// aapt resource value: 0x7f09003c
			public const int option_overlays = 2131296316;
			
			// aapt resource value: 0x7f09004d
			public const int option_pedestrian_navigation = 2131296333;
			
			// aapt resource value: 0x7f09004b
			public const int option_poi_tracking = 2131296331;
			
			// aapt resource value: 0x7f090042
			public const int option_real_reach = 2131296322;
			
			// aapt resource value: 0x7f090048
			public const int option_reverse_geocoding = 2131296328;
			
			// aapt resource value: 0x7f09004a
			public const int option_routing_and_navigation = 2131296330;
			
			// aapt resource value: 0x7f090043
			public const int option_tracks = 2131296323;
			
			// aapt resource value: 0x7f090038
			public const int options_group_map = 2131296312;
			
			// aapt resource value: 0x7f090040
			public const int options_group_navigation = 2131296320;
			
			// aapt resource value: 0x7f090011
			public const int quit_navigation = 2131296273;
			
			// aapt resource value: 0x7f090061
			public const int radius = 2131296353;
			
			// aapt resource value: 0x7f09000f
			public const int re_routing = 2131296271;
			
			// aapt resource value: 0x7f09008e
			public const int real_navigation = 2131296398;
			
			// aapt resource value: 0x7f090059
			public const int reverse_geocode = 2131296345;
			
			// aapt resource value: 0x7f090069
			public const int route_calculation_failed = 2131296361;
			
			// aapt resource value: 0x7f09001e
			public const int route_cannot_be_calculated = 2131296286;
			
			// aapt resource value: 0x7f09001b
			public const int route_invalid_destination = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int route_invalid_start = 2131296284;
			
			// aapt resource value: 0x7f09001a
			public const int route_same_start_and_destination = 2131296282;
			
			// aapt resource value: 0x7f090085
			public const int route_type_bicycle_fast = 2131296389;
			
			// aapt resource value: 0x7f090087
			public const int route_type_bicycle_quiet = 2131296391;
			
			// aapt resource value: 0x7f090086
			public const int route_type_bicycle_short = 2131296390;
			
			// aapt resource value: 0x7f090083
			public const int route_type_car_efficient = 2131296387;
			
			// aapt resource value: 0x7f090081
			public const int route_type_car_fastest = 2131296385;
			
			// aapt resource value: 0x7f090082
			public const int route_type_car_shortest = 2131296386;
			
			// aapt resource value: 0x7f090084
			public const int route_type_pedestrian = 2131296388;
			
			// aapt resource value: 0x7f09001d
			public const int route_unknown_server_error = 2131296285;
			
			// aapt resource value: 0x7f09001f
			public const int routing_server_error = 2131296287;
			
			// aapt resource value: 0x7f09005e
			public const int search = 2131296350;
			
			// aapt resource value: 0x7f090060
			public const int search_topic = 2131296352;
			
			// aapt resource value: 0x7f09005f
			public const int searching = 2131296351;
			
			// aapt resource value: 0x7f090015
			public const int searching_for_gps_label = 2131296277;
			
			// aapt resource value: 0x7f090004
			public const int seconds_value = 2131296260;
			
			// aapt resource value: 0x7f09007c
			public const int select_via_point = 2131296380;
			
			// aapt resource value: 0x7f090010
			public const int settings_label = 2131296272;
			
			// aapt resource value: 0x7f090078
			public const int settings_nav_ui = 2131296376;
			
			// aapt resource value: 0x7f09006a
			public const int show_heat_map = 2131296362;
			
			// aapt resource value: 0x7f090090
			public const int sim_from_log_navigation = 2131296400;
			
			// aapt resource value: 0x7f09008f
			public const int simulation_navigation = 2131296399;
			
			// aapt resource value: 0x7f090077
			public const int start_free_drive = 2131296375;
			
			// aapt resource value: 0x7f090076
			public const int start_free_walk = 2131296374;
			
			// aapt resource value: 0x7f090064
			public const int start_navigation = 2131296356;
			
			// aapt resource value: 0x7f090073
			public const int start_point_nav = 2131296371;
			
			// aapt resource value: 0x7f09002f
			public const int start_prim_navigation = 2131296303;
			
			// aapt resource value: 0x7f09000e
			public const int starting_pos_label = 2131296270;
			
			// aapt resource value: 0x7f090063
			public const int stop_navigation = 2131296355;
			
			// aapt resource value: 0x7f09005c
			public const int street = 2131296348;
			
			// aapt resource value: 0x7f090092
			public const int ten = 2131296402;
			
			// aapt resource value: 0x7f090096
			public const int ten_mi_h = 2131296406;
			
			// aapt resource value: 0x7f09008d
			public const int three_routes = 2131296397;
			
			// aapt resource value: 0x7f090094
			public const int twelve = 2131296404;
			
			// aapt resource value: 0x7f090098
			public const int twelve_mi_h = 2131296408;
			
			// aapt resource value: 0x7f09008c
			public const int two_routes = 2131296396;
			
			// aapt resource value: 0x7f09002e
			public const int unblock_all = 2131296302;
			
			// aapt resource value: 0x7f09006d
			public const int update_label = 2131296365;
			
			// aapt resource value: 0x7f090012
			public const int via_point_reached = 2131296274;
			
			// aapt resource value: 0x7f09000b
			public const int yards_label = 2131296267;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a000f
			public const int alt_routes_button_style = 2131361807;
			
			// aapt resource value: 0x7f0a0009
			public const int alternate_route_cell_style = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int alternate_route_cell_style_landscape = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int alternate_route_text_holder_style = 2131361803;
			
			// aapt resource value: 0x7f0a0007
			public const int alternate_route_text_style_normal = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int alternate_route_text_style_tvdpi = 2131361800;
			
			// aapt resource value: 0x7f0a0010
			public const int button_style = 2131361808;
			
			// aapt resource value: 0x7f0a0000
			public const int general_black_button_label_normal_screen = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int general_white_button_label = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int general_white_button_label_normal_screen = 2131361794;
			
			// aapt resource value: 0x7f0a000d
			public const int list_items_style = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int menu_options_group_style = 2131361806;
			
			// aapt resource value: 0x7f0a000c
			public const int menu_options_style = 2131361804;
			
			// aapt resource value: 0x7f0a0004
			public const int navigation_settings_layout = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int navigation_settings_text = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int navigation_settings_text_normal = 2131361798;
			
			// aapt resource value: 0x7f0a0003
			public const int pre_navigation_text = 2131361795;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int settings = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
