#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Skobbler.SdkDemo.Resource", IsApplication=true)]

namespace Skobbler.SdkDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int black = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int blue_filling = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int blue_outline = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int darker_grey = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int grey = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int grey_options_group = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int selected = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int white = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_background_selected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dot_full = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_details_favorite_inactive = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_dropdownmenu_bike = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_dropdownmenu_car = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_dropdownmenu_pedestrian = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_map_popup_navigate = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_searchcenter_favorite = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int logo_skobbler_by_scout = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int map_background = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int menu_options_selector = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int option_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rounded_corners = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int splashscreen_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int texture_map_unavailable = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002c
			public const int alt_route_1 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int alt_route_2 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int alt_route_3 = 2131165230;
			
			// aapt resource value: 0x7f07000c
			public const int alt_routes = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int bottom_button = 2131165198;
			
			// aapt resource value: 0x7f07004c
			public const int bottom_text = 2131165260;
			
			// aapt resource value: 0x7f070009
			public const int chess_board_background = 2131165193;
			
			// aapt resource value: 0x7f07001b
			public const int chess_table_background = 2131165211;
			
			// aapt resource value: 0x7f070011
			public const int customView = 2131165201;
			
			// aapt resource value: 0x7f07002f
			public const int custom_layout = 2131165231;
			
			// aapt resource value: 0x7f07001c
			public const int details = 2131165212;
			
			// aapt resource value: 0x7f070001
			public const int download_button = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int download_percentage_text = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int download_progress_bar = 2131165184;
			
			// aapt resource value: 0x7f07004f
			public const int draw_button = 2131165263;
			
			// aapt resource value: 0x7f07002b
			public const int exit_real_reach = 2131165227;
			
			// aapt resource value: 0x7f070007
			public const int frameLayout = 2131165191;
			
			// aapt resource value: 0x7f070023
			public const int gpx_chicago = 2131165219;
			
			// aapt resource value: 0x7f07001f
			public const int gpx_route_1 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int gpx_route_2 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int gpx_route_3 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int gpx_route_4 = 2131165218;
			
			// aapt resource value: 0x7f070010
			public const int heading_button = 2131165200;
			
			// aapt resource value: 0x7f070046
			public const int indicator_children_available = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int label_list_item = 2131165255;
			
			// aapt resource value: 0x7f070004
			public const int label_operation_in_progress = 2131165188;
			
			// aapt resource value: 0x7f070017
			public const int latitude = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int latitude_field = 2131165206;
			
			// aapt resource value: 0x7f070049
			public const int left_image = 2131165257;
			
			// aapt resource value: 0x7f070024
			public const int linearLayout1 = 2131165220;
			
			// aapt resource value: 0x7f070005
			public const int list_view = 2131165189;
			
			// aapt resource value: 0x7f070019
			public const int longitude = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int longitude_field = 2131165208;
			
			// aapt resource value: 0x7f070006
			public const int map_layout_root = 2131165190;
			
			// aapt resource value: 0x7f070030
			public const int map_style_day = 2131165232;
			
			// aapt resource value: 0x7f070033
			public const int map_style_grayscale = 2131165235;
			
			// aapt resource value: 0x7f070031
			public const int map_style_night = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int map_style_outdoor = 2131165234;
			
			// aapt resource value: 0x7f07000d
			public const int map_styles = 2131165197;
			
			// aapt resource value: 0x7f07004a
			public const int mid_layout = 2131165258;
			
			// aapt resource value: 0x7f070042
			public const int option_address_search = 2131165250;
			
			// aapt resource value: 0x7f07003e
			public const int option_alt_routes = 2131165246;
			
			// aapt resource value: 0x7f070039
			public const int option_annotations = 2131165241;
			
			// aapt resource value: 0x7f070044
			public const int option_category_search = 2131165252;
			
			// aapt resource value: 0x7f070036
			public const int option_heat_map = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int option_map_creator = 2131165239;
			
			// aapt resource value: 0x7f070034
			public const int option_map_display = 2131165236;
			
			// aapt resource value: 0x7f07003a
			public const int option_map_interaction = 2131165242;
			
			// aapt resource value: 0x7f070035
			public const int option_map_styles = 2131165237;
			
			// aapt resource value: 0x7f07003c
			public const int option_map_updates = 2131165244;
			
			// aapt resource value: 0x7f07003b
			public const int option_map_xml_and_downloads = 2131165243;
			
			// aapt resource value: 0x7f070043
			public const int option_nearby_search = 2131165251;
			
			// aapt resource value: 0x7f070038
			public const int option_overlays = 2131165240;
			
			// aapt resource value: 0x7f070041
			public const int option_poi_tracking = 2131165249;
			
			// aapt resource value: 0x7f07003f
			public const int option_real_reach = 2131165247;
			
			// aapt resource value: 0x7f070045
			public const int option_reverse_geocoding = 2131165253;
			
			// aapt resource value: 0x7f07003d
			public const int option_routing_and_navigation = 2131165245;
			
			// aapt resource value: 0x7f070040
			public const int option_tracks = 2131165248;
			
			// aapt resource value: 0x7f07000b
			public const int options_menu = 2131165195;
			
			// aapt resource value: 0x7f070048
			public const int popup_layout = 2131165256;
			
			// aapt resource value: 0x7f07000f
			public const int position_me_button = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int radius = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int radius_field = 2131165202;
			
			// aapt resource value: 0x7f070029
			public const int real_reach_bike_button = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int real_reach_car_button = 2131165226;
			
			// aapt resource value: 0x7f07000a
			public const int real_reach_layout = 2131165194;
			
			// aapt resource value: 0x7f070028
			public const int real_reach_pedestrian_button = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int real_reach_seekbar = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int real_reach_time = 2131165222;
			
			// aapt resource value: 0x7f07001d
			public const int reverse_geocode_button = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int reverse_geocoding_result = 2131165214;
			
			// aapt resource value: 0x7f07001a
			public const int search_button = 2131165210;
			
			// aapt resource value: 0x7f070015
			public const int search_topic = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int search_topic_field = 2131165204;
			
			// aapt resource value: 0x7f070003
			public const int show_heat_map = 2131165187;
			
			// aapt resource value: 0x7f07004e
			public const int subtitle = 2131165262;
			
			// aapt resource value: 0x7f070025
			public const int time_label = 2131165221;
			
			// aapt resource value: 0x7f07004d
			public const int title = 2131165261;
			
			// aapt resource value: 0x7f07004b
			public const int top_text = 2131165259;
			
			// aapt resource value: 0x7f070008
			public const int view_group_map = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_download = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_map = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_nearby_search = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_new_map = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_reverse_geocoding = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_splash = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_tracks = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int element_real_reach = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int layout_alternative_routes = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int layout_custom_view = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int layout_map_styles = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int layout_menu = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int layout_package_list_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int layout_popup = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int layout_search_list_item = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int layout_track_element_list_item = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050029
			public const int calculate_route = 2131034153;
			
			// aapt resource value: 0x7f050036
			public const int cancel_label = 2131034166;
			
			// aapt resource value: 0x7f050022
			public const int city = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int country_code = 2131034145;
			
			// aapt resource value: 0x7f050033
			public const int gpx_license_notification_text = 2131034163;
			
			// aapt resource value: 0x7f050037
			public const int gpx_route_1 = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int gpx_route_2 = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int gpx_route_3 = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int gpx_route_4 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int gpx_route_5 = 2131034171;
			
			// aapt resource value: 0x7f050024
			public const int house_number = 2131034148;
			
			// aapt resource value: 0x7f05001c
			public const int label_download = 2131034140;
			
			// aapt resource value: 0x7f05002c
			public const int label_draw = 2131034156;
			
			// aapt resource value: 0x7f05002f
			public const int label_heading = 2131034159;
			
			// aapt resource value: 0x7f05001b
			public const int label_parsing_xml = 2131034139;
			
			// aapt resource value: 0x7f05002e
			public const int label_position_me = 2131034158;
			
			// aapt resource value: 0x7f05002d
			public const int label_route = 2131034157;
			
			// aapt resource value: 0x7f05001e
			public const int latitude = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int longitude = 2131034143;
			
			// aapt resource value: 0x7f050016
			public const int map_style_day = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int map_style_grayscale = 2131034137;
			
			// aapt resource value: 0x7f050017
			public const int map_style_night = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int map_style_outdoor = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int navigate = 2131034138;
			
			// aapt resource value: 0x7f05001d
			public const int no_internet_connection = 2131034141;
			
			// aapt resource value: 0x7f050030
			public const int no_position_available = 2131034160;
			
			// aapt resource value: 0x7f050034
			public const int ok_text = 2131034164;
			
			// aapt resource value: 0x7f05000e
			public const int option_address_search = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int option_alternative_routes = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int option_annotations = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int option_category_search = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int option_group_searches = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int option_heat_map = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int option_map_creator = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int option_map_display = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int option_map_styles = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int option_map_updates = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int option_map_xml_and_downloads = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int option_nearby_search = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int option_other_map = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int option_overlays = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int option_poi_tracking = 2131034132;
			
			// aapt resource value: 0x7f05000b
			public const int option_real_reach = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int option_reverse_geocoding = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int option_routing_and_navigation = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int option_tracks = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int options_group_map = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int options_group_navigation = 2131034121;
			
			// aapt resource value: 0x7f050028
			public const int radius = 2131034152;
			
			// aapt resource value: 0x7f050020
			public const int reverse_geocode = 2131034144;
			
			// aapt resource value: 0x7f050031
			public const int route_calculation_failed = 2131034161;
			
			// aapt resource value: 0x7f050025
			public const int search = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int search_topic = 2131034151;
			
			// aapt resource value: 0x7f050026
			public const int searching = 2131034150;
			
			// aapt resource value: 0x7f050032
			public const int show_heat_map = 2131034162;
			
			// aapt resource value: 0x7f05002b
			public const int start_navigation = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int stop_navigation = 2131034154;
			
			// aapt resource value: 0x7f050023
			public const int street = 2131034147;
			
			// aapt resource value: 0x7f050035
			public const int update_label = 2131034165;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060003
			public const int alt_routes_button_style = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button_style = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int list_items_style = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int menu_options_group_style = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int menu_options_style = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
